# Profil enterprise (P1-P2) — s'ajoute à docker-compose.yml :
#   docker compose -f docker-compose.yml -f docker-compose.enterprise.yml up -d
services:
  gateway:
    image: traefik:v3.1
    command: ["--providers.docker","--entrypoints.web.address=:80","--metrics.prometheus=true"]
    ports: ["80:80"]
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"]
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: ["start-dev"]
    environment: { KEYCLOAK_ADMIN: admin, KEYCLOAK_ADMIN_PASSWORD: admin }
    ports: ["8080:8080"]
  vault:
    image: hashicorp/vault:1.17
    environment: { VAULT_DEV_ROOT_TOKEN_ID: olive-dev }
    ports: ["8200:8200"]
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment: { discovery.type: single-node, DISABLE_SECURITY_PLUGIN: "true" }
    ports: ["9200:9200"]
  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    ports: ["4317:4317"]
  prometheus:
    image: prom/prometheus:v2.53.0
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:11.1.0
    ports: ["3001:3000"]
  loki:
    image: grafana/loki:3.1.0
    ports: ["3100:3100"]
