// Source : docs/reference/olive-demo.html 25970-26040 (CPSI_GROUPES) + 26069-26205 (CPSI_SCENARIOS) — porté verbatim.
// Données du profilage continu (CPSI) : groupes de clients (prédicats) + scénarios (seuils par groupe).
export const CPSI_GROUPES: any[] = [
// Type d'entité
{ id: "G-PP", fam: "Type d'entité", label: "Personnes physiques", priorite: 80, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "PP" }] } },
{ id: "G-SOCOP", fam: "Type d'entité", label: "Sociétés opérationnelles", priorite: 80, predicat: { logique: "ET", conditions: [{ champ: "type", op: "in", val: ["SA", "SARL"] }] } },
{ id: "G-DOM", fam: "Type d'entité", label: "Sociétés de domicile", priorite: 75, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "DOM" }] } },
{ id: "G-TRUSTFOND", fam: "Type d'entité", label: "Trusts & fondations", priorite: 70, predicat: { logique: "ET", conditions: [{ champ: "type", op: "in", val: ["TRUST", "FOND"] }] } },
{ id: "G-FO", fam: "Type d'entité", label: "Family offices", priorite: 70, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "FO" }] } },
{ id: "G-FUND", fam: "Type d'entité", label: "Fonds de placement", priorite: 70, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "FUND" }] } },
{ id: "G-HOLD", fam: "Type d'entité", label: "Holdings", priorite: 75, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "HOLD" }] } },
// Secteur
{ id: "G-NEGENE", fam: "Secteur", label: "Négoce & Énergie", priorite: 60, predicat: { logique: "OU", conditions: [{ champ: "secteur", op: "eq", val: "Négoce matières premières" }, { champ: "secteur", op: "eq", val: "Energie" }] }, bareme: { poids_signaux: { velocite_tx: 11 } } },
{ id: "G-IMMO", fam: "Secteur", label: "Immobilier", priorite: 65, predicat: { logique: "ET", conditions: [{ champ: "secteur", op: "eq", val: "Immobilier" }] } },
{ id: "G-PE", fam: "Secteur", label: "Private equity", priorite: 65, predicat: { logique: "ET", conditions: [{ champ: "secteur", op: "eq", val: "Private equity" }] } },
{ id: "G-FIN", fam: "Secteur", label: "Finance & Asset management", priorite: 65, predicat: { logique: "ET", conditions: [{ champ: "secteur", op: "eq", val: "Finance & Asset management" }] } },
// AUM
{ id: "G-MASS", fam: "AUM", label: "Mass Affluent", priorite: 85, predicat: { logique: "ET", conditions: [{ champ: "aum_band", op: "eq", val: "Mass Affluent" }] } },
{ id: "G-AFF", fam: "AUM", label: "Affluent", priorite: 85, predicat: { logique: "ET", conditions: [{ champ: "aum_band", op: "eq", val: "Affluent" }] } },
{ id: "G-HNWI", fam: "AUM", label: "HNWI", priorite: 82, predicat: { logique: "ET", conditions: [{ champ: "aum_band", op: "eq", val: "HNWI" }] } },
{ id: "G-UHNWI", fam: "AUM", label: "UHNWI", priorite: 78, predicat: { logique: "ET", conditions: [{ champ: "aum_band", op: "eq", val: "UHNWI" }] } },
// Juridiction
{ id: "G-OFFSHORE", fam: "Juridiction", label: "Structures offshore à risque", priorite: 30, predicat: { logique: "ET", conditions: [{ champ: "pays_risque", op: "gte", val: 2 }] }, bareme: { bandes: [30, 55] } },
{ id: "G-CHDOM", fam: "Juridiction", label: "Domestique Suisse", priorite: 80, predicat: { logique: "ET", conditions: [{ champ: "countryCode", op: "eq", val: "CH" }] } },
{ id: "G-CROSSJUR", fam: "Juridiction", label: "Fortement transfrontalier", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "ratio_cross_border", op: "gte", val: 0.6 }] } },
// PEP & risque
{ id: "G-PEP", fam: "PEP & risque", label: "Personnes politiquement exposées", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "pep", op: "eq", val: true }] }, bareme: { bandes: [25, 50] } },
{ id: "G-HIGHRISK", fam: "PEP & risque", label: "Score de risque élevé", priorite: 20, predicat: { logique: "ET", conditions: [{ champ: "risk_band", op: "eq", val: "HIGH" }] } },
{ id: "G-ANCIEN", fam: "PEP & risque", label: "Relation ancienne (≥5 ans)", priorite: 88, predicat: { logique: "ET", conditions: [{ champ: "anciennete", op: "gte", val: 5 }] } },
// Comportement transactionnel (after-market)
{ id: "G-VELO", fam: "Transactionnel", label: "Vélocité transactionnelle élevée", priorite: 40, predicat: { logique: "ET", conditions: [{ champ: "tx_par_mois", op: "gte", val: 45 }] } },
{ id: "G-CASH", fam: "Transactionnel", label: "Intensité cash", priorite: 40, predicat: { logique: "ET", conditions: [{ champ: "ratio_cash", op: "gte", val: 0.4 }] } },
{ id: "G-STRUCT", fam: "Transactionnel", label: "Indices de fractionnement", priorite: 25, predicat: { logique: "ET", conditions: [{ champ: "score_structuration", op: "gte", val: 70 }] } },
{ id: "G-RAPIDE", fam: "Transactionnel", label: "Mouvements rapides in/out", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "rapidite_in_out", op: "gte", val: 75 }] } },
{ id: "G-DORMANT", fam: "Transactionnel", label: "Réveil de compte dormant", priorite: 25, predicat: { logique: "ET", conditions: [{ champ: "dormance_puis_actif", op: "eq", val: 1 }] } },
// Custody / settlement
{ id: "G-CUSTODY", fam: "Custody", label: "Rotation de titres élevée", priorite: 40, predicat: { logique: "ET", conditions: [{ champ: "rotation_titres", op: "gte", val: 2 }] } },
{ id: "G-FOPG", fam: "Custody", label: "Livraisons franco de paiement", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "fop_deliveries", op: "gte", val: 8 }] } },
{ id: "G-TIERSG", fam: "Custody", label: "Règlements de tiers fréquents", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "reglements_tiers", op: "gte", val: 7 }] } },
// Abus de marché (MAR)
{ id: "G-PRENEWS", fam: "Abus de marché", label: "Trades avant annonce", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "trades_pre_annonce", op: "gte", val: 3 }] } },
{ id: "G-SPOOF", fam: "Abus de marché", label: "Ratio d'annulation élevé (spoofing)", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "ratio_annulation_ordres", op: "gte", val: 0.6 }] } },
{ id: "G-WASH", fam: "Abus de marché", label: "Wash trades signalés", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "wash_trade_flags", op: "gte", val: 1 }] } },
{ id: "G-INSIDER-DECL", fam: "Abus de marché", label: "Initiés déclarés (liste MAR, R75)", priorite: 10, predicat: { logique: "ET", conditions: [{ champ: "insider", op: "eq", val: true }] }, bareme: { bandes: [25, 50] } },
// Transferts & correspondances
{ id: "G-WIRE-HRJ", fam: "Transferts", label: "Virements juridictions à risque", priorite: 20, predicat: { logique: "ET", conditions: [{ champ: "wires_high_risk_jur", op: "gte", val: 5 }] } },
{ id: "G-PASSTHRU", fam: "Transferts", label: "Pass-through (entrée-sortie même jour)", priorite: 18, predicat: { logique: "ET", conditions: [{ champ: "wires_same_day_inout", op: "gte", val: 5 }] }, bareme: { bandes: [30, 55] } },
{ id: "G-FUNNEL", fam: "Transferts", label: "Comptes entonnoir (funnel)", priorite: 22, predicat: { logique: "ET", conditions: [{ champ: "funnel_sources", op: "gte", val: 20 }] } },
{ id: "G-3PWIRE", fam: "Transferts", label: "Virements vers tiers fréquents", priorite: 25, predicat: { logique: "ET", conditions: [{ champ: "wires_third_party", op: "gte", val: 6 }] } },
// Post-marché & trading
{ id: "G-ILLIQ", fam: "Post-marché & trading", label: "Trading titres illiquides", priorite: 20, predicat: { logique: "ET", conditions: [{ champ: "illiquid_ratio", op: "gte", val: 0.5 }] } },
{ id: "G-CHURN", fam: "Post-marché & trading", label: "Rotation excessive (churning)", priorite: 22, predicat: { logique: "ET", conditions: [{ champ: "churn_ratio", op: "gte", val: 5 }] } },
{ id: "G-CROSSTRADE", fam: "Post-marché & trading", label: "Cross trades comptes liés", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "cross_trades_related", op: "gte", val: 3 }] } },
// Capital markets / CIB
{ id: "G-CAPCALL", fam: "Capital markets", label: "Appels de capitaux fréquents", priorite: 30, predicat: { logique: "ET", conditions: [{ champ: "capital_calls", op: "gte", val: 6 }] } },
{ id: "G-PRIVPLACE", fam: "Capital markets", label: "Placements privés non cotés", priorite: 25, predicat: { logique: "ET", conditions: [{ champ: "private_placements", op: "gte", val: 4 }] } },
{ id: "G-IPOFLOW", fam: "Capital markets", label: "Flux IPO / pre-IPO", priorite: 28, predicat: { logique: "ET", conditions: [{ champ: "ipo_flows", op: "gte", val: 4 }] } },
{ id: "G-UNLISTED", fam: "Capital markets", label: "Investissements non cotés / SPV", priorite: 28, predicat: { logique: "ET", conditions: [{ champ: "unlisted_investments", op: "gte", val: 5 }] } },
{ id: "G-CASHDEP", fam: "Cash & espèces", label: "Dépôts espèces importants", priorite: 25, predicat: { logique: "ET", conditions: [{ champ: "cash_deposits", op: "gte", val: 6 }] } },
// Classe d'actifs (pour cibler les scénarios de trading/pump&dump par asset)
{ id: "G-AST-ACTIONS", fam: "Classe d'actifs", label: "Actifs — Actions", priorite: 50, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Actions" }] } },
{ id: "G-AST-OBLIG", fam: "Classe d'actifs", label: "Actifs — Obligations", priorite: 50, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Obligations" }] } },
{ id: "G-AST-CRYPTO", fam: "Classe d'actifs", label: "Actifs — Crypto", priorite: 20, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Crypto" }] }, bareme: { bandes: [30, 55] } },
{ id: "G-AST-STRUCT", fam: "Classe d'actifs", label: "Actifs — Produits structurés", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Produits structurés" }] } },
{ id: "G-AST-FUND", fam: "Classe d'actifs", label: "Actifs — Fonds / ETF", priorite: 55, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Fonds / ETF" }] } },
{ id: "G-AST-PENNY", fam: "Classe d'actifs", label: "Actifs — Penny stocks", priorite: 15, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Penny stocks" }] }, bareme: { bandes: [25, 50] } },
{ id: "G-AST-COMMOD", fam: "Classe d'actifs", label: "Actifs — Matières premières", priorite: 40, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "Matières premières" }] } },
{ id: "G-AST-FX", fam: "Classe d'actifs", label: "Actifs — FX / Dérivés", priorite: 35, predicat: { logique: "ET", conditions: [{ champ: "asset_dominant", op: "eq", val: "FX / Dérivés" }] } },
{ id: "G-PUMPDUMP", fam: "Post-marché & trading", label: "Signaux pump & dump", priorite: 12, predicat: { logique: "ET", conditions: [{ champ: "pump_dump_score", op: "gte", val: 55 }] }, bareme: { bandes: [25, 45] } },
// Combinés (couple / triple) — démonstration de composabilité
{ id: "G-UHNWI-TRADER", fam: "Combinés", label: "UHNWI trader énergie/négoce (couple)", priorite: 12, predicat: { logique: "ET", conditions: [{ champ: "aum_band", op: "eq", val: "UHNWI" }, { champ: "secteur", op: "in", val: ["Négoce matières premières", "Energie"] }] }, bareme: { bandes: [30, 55] } },
{ id: "G-PP-OFF-PEP", fam: "Combinés", label: "PP offshore PEP (triple)", priorite: 8, predicat: { logique: "ET", conditions: [{ champ: "type", op: "eq", val: "PP" }, { champ: "pays_risque", op: "gte", val: 2 }, { champ: "pep", op: "eq", val: true }] }, bareme: { bandes: [20, 45] } },
];
export const CPSI_SCENARIOS: any[] = [
// ══ DOMAINE 1 — Cash & espèces (placement/intégration, LBA) ══
{ id: "SCN-STRUCT", fam: "Cash & espèces", label: "Fractionnement (structuring)", champ: "score_structuration", sens: "gte",
desc: "Depots fractionnes sous les seuils de declaration pour eviter la detection (smurfing). Typologie LBA de premiere etape.",
groupes_seuils: { "G-OFFSHORE": 60, "G-NEGENE": 75, "G-MASS": 80 } },
{ id: "SCN-CASH", fam: "Cash & espèces", label: "Intensité cash", champ: "ratio_cash", sens: "gte",
desc: "Part anormalement elevee d'especes dans l'activite, incoherente avec le profil. Signal de placement de fonds.",
groupes_seuils: { "G-MASS": 0.35, "G-NEGENE": 0.55 } },
{ id: "SCN-CASHDEP", fam: "Cash & espèces", label: "Dépôts espèces importants", champ: "cash_deposits", sens: "gte",
desc: "Depots en especes recurrents ou importants sans justification economique. Risque de placement de fonds d'origine illicite.",
groupes_seuils: { "G-CASHDEP": 6, "G-MASS": 5, "G-NEGENE": 7 } },
{ id: "SCN-CASHWD", fam: "Cash & espèces", label: "Retraits espèces importants", champ: "cash_withdrawals", sens: "gte",
desc: "Retraits en especes significatifs, potentiellement pour rompre la tracabilite. Etape d'integration.",
groupes_seuils: { "G-MASS": 5, "G-CASHDEP": 6 } },
// ══ DOMAINE 2 — Transferts & transfer agent (flux, reglement-livraison) ══
{ id: "SCN-WIRE-HRJ", fam: "Transferts & transfer agent", label: "Virements vers juridictions à risque", champ: "wires_high_risk_jur", sens: "gte",
desc: "Virements vers/depuis des juridictions a haut risque (listes FATF/SECO). Exposition geographique inhabituelle.",
groupes_seuils: { "G-WIRE-HRJ": 5, "G-OFFSHORE": 4, "G-UHNWI": 8 } },
{ id: "SCN-PASSTHRU", fam: "Transferts & transfer agent", label: "Pass-through — entrée/sortie même jour", champ: "wires_same_day_inout", sens: "gte",
desc: "Fonds entrant et ressortant le meme jour : le compte sert de relais (transit), pas d'epargne.",
groupes_seuils: { "G-PASSTHRU": 5, "G-OFFSHORE": 4 } },
{ id: "SCN-3PWIRE", fam: "Transferts & transfer agent", label: "Virements vers tiers non liés", champ: "wires_third_party", sens: "gte",
desc: "Virements frequents vers des tiers non lies au client. Rupture du lien economique attendu.",
groupes_seuils: { "G-3PWIRE": 6, "G-OFFSHORE": 5 } },
{ id: "SCN-STRUCTW", fam: "Transferts & transfer agent", label: "Virements structurés (sous seuil)", champ: "wires_structured", sens: "gte",
desc: "Virements multiples juste sous le seuil de declaration. Structuration par virement.",
groupes_seuils: { "G-MASS": 3, "G-PASSTHRU": 4 } },
{ id: "SCN-FUNNEL", fam: "Transferts & transfer agent", label: "Comptes entonnoir (multi-sources)", champ: "funnel_sources", sens: "gte",
desc: "Compte alimente par de nombreuses sources distinctes puis vide (funnel account). Collecte-consolidation.",
groupes_seuils: { "G-FUNNEL": 20, "G-OFFSHORE": 18 } },
{ id: "SCN-FOP", fam: "Transferts & transfer agent", label: "Livraisons franco de paiement (FOP)", champ: "fop_deliveries", sens: "gte",
desc: "Livraisons de titres franco de paiement, sans contrepartie cash. Transfert de valeur hors flux monetaire (transfer agent).",
groupes_seuils: { "G-CUSTODY": 9, "G-FUND": 7, "G-FO": 7 } },
{ id: "SCN-INSPECIE", fam: "Transferts & transfer agent", label: "Transferts in-specie", champ: "transferts_in_specie", sens: "gte",
desc: "Transferts de titres en nature (in-specie) inhabituels. Contournement possible du controle reglement-livraison.",
groupes_seuils: { "G-CUSTODY": 6, "G-TRUSTFOND": 4 } },
{ id: "SCN-TIERS", fam: "Transferts & transfer agent", label: "Règlements de tiers", champ: "reglements_tiers", sens: "gte",
desc: "Reglements pour le compte de tiers : le donneur d'ordre differe du beneficiaire economique.",
groupes_seuils: { "G-OFFSHORE": 7, "G-CUSTODY": 6 } },
{ id: "SCN-ROTATION", fam: "Transferts & transfer agent", label: "Rotation de titres anormale", champ: "rotation_titres", sens: "gte",
desc: "Rotation de titres anormalement elevee en conservation. Activite incoherente avec un mandat de detention.",
groupes_seuils: { "G-CUSTODY": 2.5, "G-FUND": 2, "G-HNWI": 2.2 } },
// ══ DOMAINE 3 — Activité transactionnelle (transaction monitoring) ══
{ id: "SCN-VELO", fam: "Activité transactionnelle", label: "Vélocité transactionnelle anormale", champ: "tx_par_mois", sens: "gte",
desc: "Nombre de transactions par mois anormalement eleve pour le segment. Velocite incoherente avec le profil.",
groupes_seuils: { "G-MASS": 38, "G-HNWI": 55, "G-UHNWI": 80, "G-VELO": 70 } },
{ id: "SCN-VOLUME", fam: "Activité transactionnelle", label: "Volume mensuel inhabituel (CHF)", champ: "volume_tx_mensuel_chf", sens: "gte",
desc: "Volume mensuel inhabituel au regard du patrimoine declare. Incoherence montant/profil.",
groupes_seuils: { "G-MASS": 150000, "G-HNWI": 2000000, "G-UHNWI": 30000000 } },
{ id: "SCN-RAPIDE", fam: "Activité transactionnelle", label: "Mouvements rapides in/out", champ: "rapidite_in_out", sens: "gte",
desc: "Mouvements rapides entree/sortie de fonds. Le compte ne conserve pas les avoirs (pass-through de tresorerie).",
groupes_seuils: { "G-OFFSHORE": 65, "G-CROSSJUR": 70, "G-VELO": 80 } },
{ id: "SCN-CROSS", fam: "Activité transactionnelle", label: "Concentration transfrontalière", champ: "ratio_cross_border", sens: "gte",
desc: "Concentration des flux transfrontaliers. Exposition geographique et complexite inhabituelle.",
groupes_seuils: { "G-OFFSHORE": 0.6, "G-CHDOM": 0.4 } },
// ══ DOMAINE 4 — Trading & marchés (activité de marché) ══
{ id: "SCN-ILLIQ", fam: "Trading & marchés", label: "Trading en titres illiquides", champ: "illiquid_ratio", sens: "gte",
desc: "Trading concentre sur des titres illiquides (small caps, penny stocks). Vecteur privilegie de manipulation et de blanchiment.",
groupes_seuils: { "G-ILLIQ": 0.5, "G-PE": 0.55 } },
{ id: "SCN-CHURN", fam: "Trading & marchés", label: "Rotation excessive (churning)", champ: "churn_ratio", sens: "gte",
desc: "Rotation excessive du portefeuille (churning) sans logique d'investissement. Generation artificielle de flux.",
groupes_seuils: { "G-CHURN": 5, "G-HNWI": 6 } },
{ id: "SCN-CROSSTR", fam: "Trading & marchés", label: "Cross trades entre comptes liés", champ: "cross_trades_related", sens: "gte",
desc: "Cross trades entre comptes lies. Transferts de valeur deguises en operations de marche.",
groupes_seuils: { "G-CROSSTRADE": 3, "G-FUND": 4 } },
// ══ DOMAINE 5 — Capital markets / CIB (investissement en capital) ══
{ id: "SCN-CAPCALL", fam: "Capital markets / CIB", label: "Appels de capitaux atypiques", champ: "capital_calls", sens: "gte",
desc: "Appels de capitaux (capital calls) PE/VC atypiques en frequence ou montant. Flux d'investissement a corroborer (SOW/SOF).",
groupes_seuils: { "G-CAPCALL": 6, "G-PE": 5, "G-FUND": 5, "G-UHNWI": 7 } },
{ id: "SCN-PRIVPLACE", fam: "Capital markets / CIB", label: "Placements privés non cotés", champ: "private_placements", sens: "gte",
desc: "Souscriptions a des placements prives non cotes. Opacite de la valorisation et de l'origine des fonds.",
groupes_seuils: { "G-PRIVPLACE": 4, "G-PE": 3, "G-FO": 4 } },
{ id: "SCN-IPO", fam: "Capital markets / CIB", label: "Flux IPO / pre-IPO inhabituels", champ: "ipo_flows", sens: "gte",
desc: "Flux lies a des IPO / pre-IPO inhabituels. Risque d'acces a information privilegiee et de placement de fonds.",
groupes_seuils: { "G-IPOFLOW": 4, "G-UHNWI": 5, "G-FIN": 4 } },
{ id: "SCN-UNLISTED", fam: "Capital markets / CIB", label: "Investissements non cotés / SPV", champ: "unlisted_investments", sens: "gte",
desc: "Investissements dans des structures non cotees / SPV. Complexite et opacite de la chaine de controle.",
groupes_seuils: { "G-UNLISTED": 5, "G-PE": 4, "G-HOLD": 5 } },
// ══ DOMAINE 6 — Abus de marché (MAR / LSFin) ══
{ id: "SCN-PRENEWS", fam: "Abus de marché", label: "Trades avant annonce (insider dealing)", champ: "trades_pre_annonce", sens: "gte",
desc: "Transactions precedant des annonces de marche (insider dealing). Exploitation possible d'information privilegiee (MAR/LSFin).",
groupes_seuils: { "G-INSIDER-DECL": 1, "G-PRENEWS": 3, "G-UHNWI": 3, "G-PP": 4 } },
{ id: "SCN-SPOOF", fam: "Abus de marché", label: "Spoofing / layering (annulations)", champ: "ratio_annulation_ordres", sens: "gte",
desc: "Ratio d'annulation d'ordres eleve (spoofing/layering). Ordres factices destines a tromper le carnet.",
groupes_seuils: { "G-SPOOF": 0.6, "G-VELO": 0.7 } },
{ id: "SCN-WASH", fam: "Abus de marché", label: "Wash trades", champ: "wash_trade_flags", sens: "gte",
desc: "Wash trades : achat et vente sans changement de propriete effectif. Creation de volume fictif.",
groupes_seuils: { "G-WASH": 1, "G-CROSSTRADE": 2 } },
{ id: "SCN-CONCENTR", fam: "Abus de marché", label: "Concentration intraday (manipulation)", champ: "concentration_intraday", sens: "gte",
desc: "Concentration intraday sur un titre (manipulation de cours). Marking / ramping du prix.",
groupes_seuils: { "G-VELO": 0.75, "G-PE": 0.7 } },
{ id: "SCN-MARKCL", fam: "Abus de marché", label: "Marquage de clôture (marking the close)", champ: "marking_close_flags", sens: "gte",
desc: "Marquage de cloture : transactions en fin de seance pour influencer le cours de reference.",
groupes_seuils: { "G-VELO": 1, "G-CROSSTRADE": 1 } },
{ id: "SCN-OFFMKT", fam: "Abus de marché", label: "Transactions à prix hors marché", champ: "off_market_trades", sens: "gte",
desc: "Transactions a des prix hors marche. Transfert de valeur ou manipulation deguisee.",
groupes_seuils: { "G-CROSSTRADE": 2, "G-ILLIQ": 3 } },
{ id: "SCN-PUMPDUMP", fam: "Abus de marché", label: "Pump & dump (toutes classes d'actifs)", champ: "pump_dump_score", sens: "gte",
desc: "Gonflement artificiel du cours puis liquidation (pump & dump). Toutes classes d'actifs, amplifie sur les illiquides.",
groupes_seuils: { "G-AST-CRYPTO": 40, "G-AST-PENNY": 40, "G-AST-STRUCT": 50, "G-AST-COMMOD": 55, "G-AST-FX": 55, "G-AST-ACTIONS": 65, "G-AST-FUND": 70, "G-AST-OBLIG": 80 } },,
    // ── Bloc 48 — Private banking (R189..R206) : paramétrables par groupe comme tous les autres ──
    { id: "SCN-PB-STRUCT", ruleRef: "R189", fam: "Private banking", label: "Fractionnement des dépôts (structuring)", champ: "score_structuration", sens: "gte", desc: "Plusieurs dépôts juste sous le seuil de déclaration sur une fenêtre glissante — leur somme dépasse le seuil agrégé.", groupes_seuils: { "G-OFFSHORE": 55, "G-HNWI": 70, "G-CASH": 60 } },
    { id: "SCN-PB-CIRCXB", ruleRef: "R190", fam: "Private banking", label: "Circuit transfrontalier circulaire", champ: "ratio_cross_border", sens: "gte", desc: "Les fonds partent à l'étranger et reviennent à leur point de départ via plusieurs juridictions, sans justification économique.", groupes_seuils: { "G-CROSSJUR": 60, "G-OFFSHORE": 55 } },
    { id: "SCN-PB-VELOC", ruleRef: "R191", fam: "Private banking", label: "Vélocité transactionnelle anormale (PB)", champ: "tx_par_mois", sens: "gte", desc: "Le volume d'opérations du compte s'écarte fortement de son rythme habituel des 90 derniers jours.", groupes_seuils: { "G-HNWI": 40, "G-DORMANT": 12 } },
    { id: "SCN-PB-SANCT", ruleRef: "R192", fam: "Private banking", label: "Contrepartie sanctionnée — blocage immédiat", champ: "wires_high_risk_jur", sens: "gte", desc: "La contrepartie figure sur une liste de sanctions (SECO, OFAC, UE, ONU) : l'opération est gelée avant exécution, décision humaine requise.", groupes_seuils: { "G-HIGHRISK": 1, "G-OFFSHORE": 1 } },
    { id: "SCN-PB-UBO", ruleRef: "R193", fam: "Private banking", label: "Ayant droit économique incohérent", champ: "reglements_tiers", sens: "gte", desc: "Le bénéficiaire réel des flux ne correspond pas à l'ayant droit déclaré au formulaire A/K.", groupes_seuils: { "G-DOM": 3, "G-OFFSHORE": 2 } },
    { id: "SCN-PB-INOUT", ruleRef: "R194", fam: "Private banking", label: "Entrée-sortie le même jour", champ: "wires_same_day_inout", sens: "gte", desc: "Des fonds déposés repartent presque intégralement le jour même — schéma d'empilage (layering).", groupes_seuils: { "G-3PWIRE": 2, "G-CASH": 2 } },
    { id: "SCN-PB-TIERS", ruleRef: "R195", fam: "Private banking", label: "Payeur tiers non documenté", champ: "wires_third_party", sens: "gte", desc: "Un tiers étranger au dossier crédite le compte sans lien documenté avec le client.", groupes_seuils: { "G-3PWIRE": 2, "G-AFF": 3 } },
    { id: "SCN-PB-RETOUR", ruleRef: "R196", fam: "Private banking", label: "Fonds revenant à leur source", champ: "funnel_sources", sens: "gte", desc: "Les fonds reviennent à leur donneur d'ordre initial en moins de trente jours, après passage par des intermédiaires.", groupes_seuils: { "G-FUNNEL": 3, "G-OFFSHORE": 2 } },
    { id: "SCN-PB-JURISK", ruleRef: "R197", fam: "Private banking", label: "Virements vers juridictions à risque (PB)", champ: "wires_high_risk_jur", sens: "gte", desc: "Des virements transitent par des juridictions de la liste à risque paramétrée par la banque.", groupes_seuils: { "G-CROSSJUR": 2, "G-HIGHRISK": 1 } },
    { id: "SCN-PB-ROND", ruleRef: "R198", fam: "Private banking", label: "Montants ronds répétés", champ: "wires_structured", sens: "gte", desc: "Des montants parfaitement ronds se répètent sans logique commerciale apparente.", groupes_seuils: { "G-HNWI": 3, "G-CASH": 3 } },
    { id: "SCN-PB-CASHWIRE", ruleRef: "R199", fam: "Private banking", label: "Espèces converties en virements", champ: "cash_deposits", sens: "gte", desc: "Des espèces déposées repartent en virements sortants dans les 48 heures — l'origine des espèces doit être documentée.", groupes_seuils: { "G-CASHDEP": 3, "G-CASH": 4 } },
    { id: "SCN-PB-PEPADJ", ruleRef: "R200", fam: "Private banking", label: "Proximité avec une personne exposée", champ: "reglements_tiers", sens: "gte", desc: "La contrepartie est un proche d'une personne politiquement exposée, identifié par le graphe des personnes liées.", groupes_seuils: { "G-HIGHRISK": 2, "G-FO": 2 } },
    { id: "SCN-PB-FACT", ruleRef: "R201", fam: "Private banking", label: "Factures systématiquement sous-payées", champ: "off_market_trades", sens: "gte", desc: "Des factures commerciales sont réglées avec un écart constant — indicateur de blanchiment par le commerce.", groupes_seuils: { "G-DOM": 2, "G-AFF": 3 } },
    { id: "SCN-PB-ROTCP", ruleRef: "R202", fam: "Private banking", label: "Rotation anormale de contreparties", champ: "churn_ratio", sens: "gte", desc: "Un nombre inhabituel de contreparties jamais vues apparaît sur une courte période.", groupes_seuils: { "G-CHURN": 55, "G-HNWI": 70 } },
    { id: "SCN-PB-CRS", ruleRef: "R203", fam: "Private banking", label: "Documentation fiscale manquante — blocage", champ: "wires_structured", sens: "gte", desc: "L'auto-certification fiscale (CRS/FATCA) est absente ou expirée : les opérations sortantes sont suspendues jusqu'à régularisation.", groupes_seuils: { "G-CROSSJUR": 1, "G-OFFSHORE": 1 } },
    { id: "SCN-PB-PROCUR", ruleRef: "R204", fam: "Private banking", label: "Abus de procuration", champ: "reglements_tiers", sens: "gte", desc: "Un fondé de pouvoir opère vers ses propres comptes, hors du périmètre de son mandat.", groupes_seuils: { "G-FO": 2, "G-ANCIEN": 2 } },
    { id: "SCN-PB-FISC", ruleRef: "R205", fam: "Private banking", label: "Montage fiscal multi-juridictions", champ: "unlisted_investments", sens: "gte", desc: "Une structure traversant plusieurs juridictions sans substance économique, à finalité fiscale exclusive.", groupes_seuils: { "G-OFFSHORE": 2, "G-FUND": 3 } },
    { id: "SCN-PB-CONC", ruleRef: "R206", fam: "Private banking", label: "Concentration sur une contrepartie unique", champ: "concentration_intraday", sens: "gte", desc: "Une part dominante des flux du compte se dirige vers une seule et même contrepartie.", groupes_seuils: { "G-HNWI": 60, "G-AFF": 55 } },
    // ── Bloc 49 — Finance islamique (R207..R221) : mêmes mécanismes, seuils par groupe ──
    { id: "SCN-IS-PROFIL", ruleRef: "R207", fam: "Finance islamique", label: "Profil islamique sur compte standard", champ: "reglements_tiers", sens: "gte", desc: "Un client au profil islamique est rattaché à un compte standard — incohérence de paramétrage à corriger.", groupes_seuils: { "G-FO": 1 } },
    { id: "SCN-IS-RIBA", ruleRef: "R208", fam: "Finance islamique", label: "Revenus d'intérêts (riba)", champ: "rotation_titres", sens: "gte", desc: "Un revenu d'intérêts est crédité sur un compte islamique : il est isolé (purification) et signalé.", groupes_seuils: { "G-FUND": 2 } },
    { id: "SCN-IS-MAYSIR", ruleRef: "R209", fam: "Finance islamique", label: "Spéculation excessive (maysir) — blocage", champ: "pump_dump_score", sens: "gte", desc: "Instrument trop spéculatif (volatilité ou levier excessifs) : l'ordre est bloqué avant exécution.", groupes_seuils: { "G-HNWI": 55 } },
    { id: "SCN-IS-GHARAR", ruleRef: "R210", fam: "Finance islamique", label: "Contrat incertain (gharar)", champ: "off_market_trades", sens: "gte", desc: "Contrat sans prix, quantité ou échéance certains : rejeté, une alternative conforme est proposée.", groupes_seuils: { "G-FUND": 2 } },
    { id: "SCN-IS-ZAKAT", ruleRef: "R211", fam: "Finance islamique", label: "Calcul annuel de la zakat (2.5%)", champ: "volume_tx_mensuel_chf", sens: "gte", desc: "Si le patrimoine dépasse le nisab, la zakat annuelle de 2.5% est calculée et proposée au paiement.", groupes_seuils: { "G-HNWI": 100000 } },
    { id: "SCN-IS-SUKUK", ruleRef: "R212", fam: "Finance islamique", label: "Authenticité des sukuk", champ: "private_placements", sens: "gte", desc: "Tout titre présenté comme sukuk doit porter une certification de board reconnue — sinon il est rejeté.", groupes_seuils: { "G-FUND": 1 } },
    { id: "SCN-IS-HALAL", ruleRef: "R213", fam: "Finance islamique", label: "Contrepartie de secteur prohibé — blocage", champ: "wires_third_party", sens: "gte", desc: "La contrepartie relève d'un secteur prohibé (alcool, jeux, armement, intérêts) : la transaction est bloquée.", groupes_seuils: { "G-3PWIRE": 1 } },
    { id: "SCN-IS-QARD", ruleRef: "R214", fam: "Finance islamique", label: "Prêt sans intérêt (qard ul hasan)", champ: "reglements_tiers", sens: "gte", desc: "Prêt à principal immuable : le remboursement doit correspondre exactement au principal, sans supplément.", groupes_seuils: { "G-AFF": 2 } },
    { id: "SCN-IS-MUDAR", ruleRef: "R215", fam: "Finance islamique", label: "Partage de profit (mudaraba)", champ: "capital_calls", sens: "gte", desc: "Le profit du trimestre est distribué selon les ratios convenus entre le client et la banque, et tracé.", groupes_seuils: { "G-CAPCALL": 2 } },
    { id: "SCN-IS-SANCT", ruleRef: "R216", fam: "Finance islamique", label: "Sanctions — vérification parallèle", champ: "wires_high_risk_jur", sens: "gte", desc: "Vérification parallèle des listes de sanctions complémentaires — revue manuelle, pas de blocage automatique.", groupes_seuils: { "G-CROSSJUR": 2 } },
    { id: "SCN-IS-AUDIT", ruleRef: "R217", fam: "Finance islamique", label: "Rapport d'audit Sharia annuel", champ: "tx_par_mois", sens: "gte", desc: "Chaque compte islamique reçoit un rapport annuel certifiant la conformité de l'exercice.", groupes_seuils: { "G-FO": 30 } },
    { id: "SCN-IS-WAQF", ruleRef: "R218", fam: "Finance islamique", label: "Dotation à principal immuable (waqf)", champ: "cash_withdrawals", sens: "gte", desc: "Le principal d'une dotation est intouchable : seuls les revenus peuvent être distribués aux bénéficiaires.", groupes_seuils: { "G-FO": 2 } },
    { id: "SCN-IS-TAKAF", ruleRef: "R219", fam: "Finance islamique", label: "Assurance mutualisée (takaful)", champ: "capital_calls", sens: "gte", desc: "Pool mutualisé de primes : l'excédent annuel est redistribué aux souscripteurs au prorata.", groupes_seuils: { "G-FUND": 2 } },
    { id: "SCN-IS-ECHSUK", ruleRef: "R220", fam: "Finance islamique", label: "Échéance de sukuk — alertes", champ: "rotation_titres", sens: "gte", desc: "Alertes à 90, 30 et 0 jours avant l'échéance d'un sukuk, avec tâches de réinvestissement conforme.", groupes_seuils: { "G-FUND": 2 } },
    { id: "SCN-IS-ESGCERT", ruleRef: "R221", fam: "Finance islamique", label: "Double certification ESG + islamique", champ: "unlisted_investments", sens: "gte", desc: "Les produits proposés aux profils islamiques doivent porter la double certification ESG et islamique.", groupes_seuils: { "G-FUND": 1 } },

];
