// Catalogue BAT (Business Acceptance Test, R333/FB) — cases de recette CLIENT, par MODULE
// licenciable. Le cahier remis à un tenant est GÉNÉRÉ d'ici, filtré par sa licence (jamais
// rédigé à la main). Chaque case : intitulé (ce que le métier vérifie) + critère d'acceptation.
// Les modules correspondent aux modules de licence vendor (R320 : KYC, AML, COC, ACCREV,
// ONBOARDING, SCREENING, PMS, IA, GED, OCR, WORKFLOWS).

export const catalogueBat = [
  { id: "BAT-KYC-01", module: "KYC", parcours: "PARC-KYC-AML",
    intitule: "Ouvrir une relation et compléter le dossier KYC jusqu'à décision.",
    critere: "Le dossier atteint un statut décidable ; la décision est tracée et à quatre yeux." },
  { id: "BAT-KYC-02", module: "KYC", parcours: "PARC-KYC-AML",
    intitule: "Rejouer le dossier à une date passée (rejeu KYC à date).",
    critere: "L'état restitué correspond à la date choisie, sans altérer l'état courant." },
  { id: "BAT-AML-01", module: "AML", parcours: "PARC-KYC-AML",
    intitule: "Générer une alerte AML et la qualifier via la matrice de décision.",
    critere: "L'alerte naît, se qualifie par le rôle habilité, la décision est journalisée." },
  { id: "BAT-COC-01", module: "COC", parcours: "PARC-COC",
    intitule: "Enregistrer un changement de circonstances et rouvrir la revue.",
    critere: "Le CoC re-jauge le risque ; la revue rouverte est tracée." },
  { id: "BAT-ACCREV-01", module: "ACCREV", parcours: "PARC-REVIEW",
    intitule: "Mener une revue périodique de bout en bout, la clôturer et la viser.",
    critere: "La revue se documente, se décide, se clôt ; le visa est apposé." },
  { id: "BAT-ONB-01", module: "ONBOARDING",
    intitule: "Suivre un onboarding avec ses jalons et son SLA.",
    critere: "Les jalons progressent ; le SLA échu est signalé, jamais silencieux." },
  { id: "BAT-SCR-01", module: "SCREENING",
    intitule: "Lancer un screening et traiter un hit potentiel.",
    critere: "Le hit est présenté, décidé par le rôle habilité, la décision est tracée." },
  { id: "BAT-PMS-01", module: "PMS",
    intitule: "Consulter un portefeuille et ses positions (PMS).",
    critere: "Les positions s'affichent ; l'accès respecte le périmètre du rôle." },
  { id: "BAT-IA-01", module: "IA", parcours: "PARC-OLIVIA",
    intitule: "Interroger Olivia sur un dossier ; obtenir une proposition (jamais une action).",
    critere: "Olivia propose une carte sourcée ; l'humain décide (R44) ; hors périmètre refusé." },
  { id: "BAT-GED-01", module: "GED",
    intitule: "Classer une pièce en GED et la retrouver, avec sa version.",
    critere: "La pièce est typée, versionnée (sha256), retrouvable ; la rétention s'applique." },
  { id: "BAT-OCR-01", module: "OCR",
    intitule: "Extraire des champs typés d'un document via OCR.",
    critere: "Les champs extraits sont typés ; l'échec d'extraction est explicite." },
  { id: "BAT-WF-01", module: "WORKFLOWS",
    intitule: "Instancier un workflow gouverné et le faire progresser.",
    critere: "Le workflow suit sa définition ; les transitions sont tracées." },
];
