/**
 * CATALOGUE D'ÉVÉNEMENTS AU WRITE (P-L5-2, dette C6 · R339/EV). Le catalogue régit l'ÉCRITURE :
 * emitEvent (common/domain-event.ts) valide le payload contre le schéma zod AVANT insertion —
 * échec = exception typée, JAMAIS d'écriture partielle — et pose eventVersion depuis le catalogue.
 * Les événements DÉJÀ stockés ne sont jamais touchés (R49) : la lecture reste régie par les
 * upcasters (modules/events/upcasters.ts).
 *
 * MIGRATION DOUCE (docs/notes/L5-events-todo.md) : les types listés dans TYPES_EN_ATTENTE (inventaire
 * généré des littéraux émis au code) passent SANS validation (eventVersion défaut 1) tant qu'ils
 * n'ont pas reçu leur schéma. Un type ABSENT des deux listes est REFUSÉ — un événement ne s'invente
 * pas au write. Faire évoluer un payload = nouvelle version ici + upcaster à la lecture, jamais un
 * UPDATE des lignes existantes.
 */
import { z } from "zod";

export type EntreeCatalogue = { version: number; schema: z.ZodTypeAny };

// ── Schémas STRICTS (v-courante) — noyau KYC (verrou R84 · passage de main R85) + screening/PEP ──
export const SCHEMAS_EVENEMENTS: Record<string, EntreeCatalogue> = {
  "kyc.lock.acquired":     { version: 1, schema: z.object({ code: z.string(), holder: z.string() }).strict() },
  "kyc.lock.released":     { version: 1, schema: z.object({ code: z.string(), by: z.string() }).strict() },
  "kyc.handoff.next":      { version: 1, schema: z.object({ code: z.string(), to: z.string(), by: z.string(), message: z.string() }).strict() },
  "kyc.handoff.back":      { version: 1, schema: z.object({ code: z.string(), to: z.string(), by: z.string(), message: z.string() }).strict() },
  "kyc.handoff.validated": { version: 1, schema: z.object({ code: z.string(), by: z.string(), message: z.string() }).strict() },
  "kyc.handoff.rejected":  { version: 1, schema: z.object({ code: z.string(), by: z.string(), message: z.string() }).strict() },
  "olivia.curseur.change": { version: 1, schema: z.object({ capacite: z.string(), niveau: z.string(),
    precedent: z.string(), par: z.string() }).strict() },
  "mros.goaml.soumis": { version: 1, schema: z.object({ reference: z.string(), par: z.string() }).strict() },
  "mros.chrono.alerte": { version: 1, schema: z.object({ communicationId: z.string(), joursOuvres: z.number(), echeanceJours: z.number() }).strict() },
  // ── Vague 1 de schématisation (2026-08-08) : familles mros.* / trip.* / training.* —
  // schémas = payloads RÉELS des sites d'émission (mros.service, businesstrip, formations).
  "mros.decision": { version: 1, schema: z.object({ decision: z.string(), motif: z.string(),
    par: z.string(), riskCaseId: z.string(), dossierSha256: z.string() }).strict() },
  "mros.notification": { version: 1, schema: z.object({ notification: z.string(), par: z.string() }).strict() },
  "mros.gel.pose": { version: 1, schema: z.object({ motif: z.string(), echeance: z.string(),
    par: z.string() }).strict() },
  "mros.gel.leve": { version: 1, schema: z.object({ motif: z.string(), par: z.string() }).strict() },
  // gelEcheance sort de Prisma en instance Date (DateTime) — validé AVANT sérialisation JSON
  "mros.gel.echeance": { version: 1, schema: z.object({ echeance: z.union([z.string(), z.date()]) }).strict() },
  "mros.acces": { version: 1, schema: z.object({ par: z.string() }).strict() },
  "mros.acces.refuse": { version: 1, schema: z.object({ par: z.string(), role: z.string() }).strict() },
  // Bloc 63 (R446) : soumission ENRICHIE — chaîne résolue risque×budget FIGÉE dans l'événement
  // de création (grandfathering R29) ; champs optionnels, les événements historiques restent valides.
  "trip.submitted": { version: 1, schema: z.object({ destinations: z.array(z.string()),
    avis: z.number(), signaux: z.number(),
    chaine: z.array(z.string()).optional(), budget: z.number().nullish(),
    origineChaine: z.object({ risque: z.string(), budget: z.number().nullish(),
      seuilBudgetHPB: z.number(), hpbAjoute: z.boolean() }).optional() }).strict() },
  "trip.visa.signed": { version: 1, schema: z.object({ role: z.string(), par: z.string(),
    motivation: z.string().optional() }).strict() },      // Bloc 63 (R447) : dérogation motivée sur avertissement
  "trip.approved": { version: 1, schema: z.object({}).strict() },
  "trip.revised": { version: 1, schema: z.object({ depuis: z.string(), revision: z.number() }).strict() },
  "trip.contactreports.manquants": { version: 1, schema: z.object({ manquants: z.array(z.string()) }).strict() },
  // ── Bloc 63 (repo R446–R452 + R465) — business trip AU MOTEUR : check consigné/invalidé,
  //    certificat de trip, relances SLA, prospect né en voyage. Payloads RÉELS des sites d'émission.
  "trip.check.consigne": { version: 1, schema: z.object({ juridictions: z.array(z.string()),
    parActivite: z.array(z.any()), referentielVersion: z.string(), at: z.string() }).strict() },   // R448 : la preuve
  "trip.check.invalide": { version: 1, schema: z.object({ cause: z.string() }).strict() },          // R448 : invalidation tracée
  "trip.certificat.soumis": { version: 1, schema: z.object({ par: z.string(), role: z.string(),
    validateurResolu: z.string(), activitesParJuridiction: z.record(z.array(z.string())),
    rencontres: z.array(z.object({ clientId: z.string(), contactReportId: z.string() }).strict()),
    ecarts: z.array(z.any()), narratif: z.string(), prospectsNes: z.array(z.any()) }).strict() },   // R450
  "trip.certificat.vise": { version: 1, schema: z.object({ par: z.string(), role: z.string() }).strict() },
  "trip.certificat.qualification.demandee": { version: 1, schema: z.object({
    ecarts: z.array(z.any()), par: z.string() }).strict() },                                        // R450/R44 : analyse humaine
  "trip.certificat.relance": { version: 1, schema: z.object({ joursRetard: z.number(),
    notifie: z.string() }).strict() },                                                              // R450 : SLA tracé
  "trip.cloture": { version: 1, schema: z.object({ par: z.string() }).strict() },                   // R450 : le certificat clôt
  "trip.prospect.ne": { version: 1, schema: z.object({ clientId: z.string(), contactReportId: z.string(),
    nom: z.string(), verdictProsp: z.any() }).strict() },                                           // R465 : origine tracée
  // ── Bloc 64 (repo R453–R462) — matrice versionnée, checks au moment de l'acte, registre RS,
  //    localisation, impact. Payloads RÉELS des sites d'émission (xb.module.ts).
  "MATRIX_SYNCED": { version: 1, schema: z.object({ versionId: z.string(), source: z.string(),
    entrees: z.array(z.any()), diff: z.array(z.object({ jurisdiction: z.string(), activite: z.string(),
      ancien: z.string().nullable(), nouveau: z.string() }).strict()), at: z.string() }).strict() },  // R453
  "xb.matrice.sync.echec": { version: 1, schema: z.object({ source: z.string(), erreur: z.string(),
    at: z.string() }).strict() },                                                                    // R453 : jamais silencieux
  "xb.tache.creee": { version: 1, schema: z.object({ type: z.string(),
    voyageId: z.string().optional(), assigneRole: z.string().optional(), rm: z.string().optional(),
    contactReportId: z.string().optional(), clientId: z.string().optional(),
    perimetre: z.string().nullish() }).strict() },                                                   // R453/R454/R456/R459
  "xb.impact.notifie": { version: 1, schema: z.object({ versionId: z.string(),
    clientsAffectes: z.number(), voyagesARevoir: z.number(), preuvesInsuffisantes: z.number() }).strict() },   // R459
  "xb.preacte.verdict": { version: 1, schema: z.object({ type: z.string(), clientId: z.string(),
    juridiction: z.string(), verdict: z.string(), passe: z.boolean(), versionMatrice: z.string(),
    at: z.string(), perimetre: z.string().optional(), condition: z.string().optional(),
    preuveId: z.string().optional(), mention: z.string().optional(), motif: z.string().optional() }).strict() },   // R455
  "xb.rs.enregistree": { version: 1, schema: z.object({ clientId: z.string(), perimetre: z.string(),
    nature: z.string(), docId: z.string(), date: z.string(), par: z.string() }).strict() },          // R456
  "xb.rs.visee": { version: 1, schema: z.object({ par: z.string() }).strict() },
  "xb.localisation.declaree": { version: 1, schema: z.object({ juridiction: z.string(),
    du: z.string(), au: z.string(), par: z.string() }).strict() },                                   // R457
  // ── Vague 3 (C6, 2026-08-08) — aml.* + cpsi.* réellement émis via emitEvent. Schémas tirés
  //    des payloads RÉELS (aml.service, aml-gap.service, aml-eval.service, cpsi.module).
  //    NB : les 11 littéraux cpsi.* restants du scan vivent dans le journal JUMEAU cpsi_events
  //    (moteur pur, rejouable) — jamais écrits via emitEvent, ils restent en attente (sur-capture
  //    assumée, cf. docs/notes/L5-events-todo.md).
  "aml.signal.leve": { version: 1, schema: z.object({ clientId: z.string(), type: z.string(),
    regle: z.string(), niveau: z.number(), bloquant: z.boolean() }).strict() },                      // R189→R206
  "aml.operation.bloquee": { version: 1, schema: z.object({ regles: z.array(z.string()) }).strict() },   // niveau 1 = suspension
  "aml.signal.raised": { version: 1, schema: z.object({ scenarioCode: z.string(),
    scenarioVer: z.number(), ruleRef: z.string(), clientId: z.string().nullable(),
    niveau: z.number().nullish(), blocking: z.boolean() }).strict() },                               // AML Gap (R340+)
  "aml.block.requested": { version: 1, schema: z.object({ scenarioCode: z.string(),
    ruleRef: z.string(), clientId: z.string().nullable(), motif: z.string() }).strict() },           // R44 : demandé, jamais exécuté
  "aml.signal.qualified": { version: 1, schema: z.object({ scenarioCode: z.string(),
    outcome: z.enum(["TP", "FP"]), motif: z.string(), par: z.string() }).strict() },                 // R7 : motif obligatoire
  "aml.eval.version_compared": { version: 1, schema: z.object({ overrides: z.any(),
    recallBefore: z.number(), recallAfter: z.number(), degradation: z.boolean(),
    regressions: z.number(), par: z.string() }).strict() },                                          // R375 : rollback PROPOSÉ
  "aml.eval.completed": { version: 1, schema: z.object({ corpus: z.number(), evaluated: z.number(),
    raised: z.number(), recall: z.number(), via2G: z.number(), deferred2G: z.number(),
    par: z.string() }).strict() },                                                                   // backtest GT (R29)
  "cpsi.sla.depassement": { version: 1, schema: z.object({ cle: z.string(), jalon: z.string(),
    enAttenteMrosJours: z.number().nullable(), par: z.string() }).strict() },                        // R250
  "cpsi.case_proposal.emitted": { version: 1, schema: z.object({ cle: z.string(),
    par: z.string() }).strict() },                                                                   // R285/R286 : miroir outbox, at corrélé au jumeau
  // ── Vague 4 (C6, 2026-08-08) — ged.* intégral : ingestion (R137–R139), noyau documentaire
  //    (R108–R112), avancé (ancrage/QES/hold/destruction), vues (R164). Payloads RÉELS.
  "ged.ingest": { version: 1, schema: z.object({ canal: z.string(), source: z.string(),
    par: z.string(), nom: z.string() }).strict() },                                                  // R137 : l'arrivée est une pièce
  "ged.classement": { version: 1, schema: z.object({ typeCode: z.string(), clientId: z.string(),
    par: z.string(), retentionUntil: z.union([z.string(), z.date()]).nullable() }).strict() },       // R138
  "ged.ocr.derive": { version: 1, schema: z.object({ versionId: z.string(), moteur: z.string(),
    sha256Derive: z.string() }).strict() },                                                          // dérivé, jamais l'original
  "ged.inbox.acces.refuse": { version: 1, schema: z.object({ par: z.string(), role: z.string() }).strict() },   // R139
  "ged.inbox.sla": { version: 1, schema: z.object({ jours: z.number(), sla: z.number() }).strict() },   // R39 : mesuré, rien ne se classe seul
  "ged.version.creee": { version: 1, schema: z.object({ numero: z.number(), sha256: z.string(),
    deposant: z.string(), type: z.string() }).strict() },                                            // R108
  "ged.archive": { version: 1, schema: z.object({ motif: z.string(), par: z.string() }).strict() },
  "ged.acces": { version: 1, schema: z.object({ lecteur: z.string(), role: z.string(),
    version: z.number() }).strict() },                                                               // R112 : qui a vu quoi
  "ged.acces.refuse": { version: 1, schema: z.object({ lecteur: z.string(), role: z.string(),
    type: z.string() }).strict() },
  "ged.consultation.refusee": { version: 1, schema: z.object({ par: z.string(), role: z.string(),
    typeCode: z.string() }).strict() },                                                              // R110
  "ged.completude.verifiee": { version: 1, schema: z.object({ passage: z.string(), complet: z.boolean(),
    manquants: z.array(z.string()), expires: z.array(z.string()) }).strict() },                      // R110 : la GED constate
  // deposeAt/retentionUntil sortent de Prisma en instance Date — validés AVANT sérialisation JSON
  "ged.expiration.detectee": { version: 1, schema: z.object({ type: z.string(),
    deposeAt: z.union([z.string(), z.date()]), validiteMois: z.number() }).strict() },
  "ged.integrite.alerte": { version: 1, schema: z.object({ version: z.number(),
    attendu: z.string(), obtenu: z.string() }).strict() },                                           // altération = jamais authentique
  "ged.externe.indisponible": { version: 1, schema: z.object({ operation: z.string(),
    message: z.string() }).strict() },                                                               // R167 : le signal n'étouffe jamais le refus
  "ged.ancrage.cree": { version: 1, schema: z.object({ racine: z.string(), tsaToken: z.string(),
    versions: z.number() }).strict() },
  "ged.signature.qualifiee": { version: 1, schema: z.object({ version: z.number(),
    signataire: z.string(), evidenceId: z.string() }).strict() },
  "ged.classification.proposee": { version: 1, schema: z.object({ type: z.string(),
    expirationDetectee: z.any().nullish(), source: z.string() }).strict() },                         // R44 : rien n'est appliqué ici
  "ged.classification.confirmee": { version: 1, schema: z.object({ type: z.string(),
    par: z.string() }).strict() },
  "ged.destruction.proposee": { version: 1, schema: z.object({
    retentionUntil: z.union([z.string(), z.date()]).nullable(), type: z.string() }).strict() },      // R33/R44 : décision, jamais une échéance
  "ged.destruction.certifiee": { version: 1, schema: z.object({ motif: z.string(), par: z.string(),
    empreintes: z.array(z.string()) }).strict() },
  "ged.hold.pose": { version: 1, schema: z.object({ motif: z.string(), par: z.string(),
    docs: z.number() }).strict() },
  "ged.hold.leve": { version: 1, schema: z.object({ motif: z.string(), par: z.string(),
    docs: z.number() }).strict() },
  "ged.vue.creee": { version: 1, schema: z.object({ code: z.string(), par: z.string() }).strict() }, // R164
  "ged.vue.evaluee": { version: 1, schema: z.object({ code: z.string(), par: z.string(),
    role: z.string(), nbServis: z.number() }).strict() },
  "ged.vue.retiree": { version: 1, schema: z.object({ code: z.string(), par: z.string(),
    motif: z.string() }).strict() },
  "ged.vue.acces.refuse": { version: 1, schema: z.object({ par: z.string(), role: z.string() }).strict() },
  // ── Vague 5 (C6, 2026-08-08) — tache.* (signaux de travail R39/R44 : le système mesure et
  //    notifie, l'humain agit) + task.* (module Tâches R38). Payloads RÉELS des sites d'émission.
  "tache.aiguillage.edd": { version: 1, schema: z.object({ proposalId: z.string(),
    cibleType: z.string(), par: z.string() }).strict() },                                            // circuit R66 — la VOIE NORMALE
  "tache.allegement.edd": { version: 1, schema: z.object({ proposalId: z.string(),
    cibleType: z.string(), par: z.string() }).strict() },
  "tache.qualification.alerte": { version: 1, schema: z.object({ proposalId: z.string(),
    cibleType: z.string(), par: z.string() }).strict() },
  "tache.coffre.reconciliation": { version: 1, schema: z.object({ cle: z.string() }).strict() },     // R147 : l'écart est un FAIT d'audit
  "tache.core.resolution": { version: 1, schema: z.object({ compteCore: z.string().nullable() }).strict() },
  "tache.corroboration": { version: 1, schema: z.object({ dossier: z.string(), rm: z.string() }).strict() },
  "tache.ged.classement": { version: 1, schema: z.object({ nom: z.string() }).strict() },            // rien ne se classe seul (R39)
  "tache.ged.destruction": { version: 1, schema: z.object({ client: z.string().nullable() }).strict() },
  "tache.ged.renouvellement": { version: 1, schema: z.object({ type: z.string(),
    client: z.string().nullable() }).strict() },
  "tache.kyc.requalification": { version: 1, schema: z.object({ origine: z.string(),
    raisons: z.array(z.string()) }).strict() },
  "tache.legal.preavis": { version: 1, schema: z.object({ id: z.string(), reference: z.string(),
    dateFin: z.string(), tacite: z.boolean(), notifie: z.array(z.string()), par: z.string() }).strict() },
  "tache.maj_ged": { version: 1, schema: z.object({ document: z.string() }).strict() },
  "tache.onboarding.relance": { version: 1, schema: z.object({ etape: z.string(),
    rm: z.string().nullable() }).strict() },
  "tache.oprisk.action.retard": { version: 1, schema: z.object({ id: z.string(), incidentId: z.string(),
    titre: z.string(), echeance: z.string(), notifie: z.array(z.string()), par: z.string() }).strict() },
  "tache.personne.completion": { version: 1, schema: z.object({ nom: z.string() }).strict() },
  "tache.pms.regularisation": { version: 1, schema: z.object({ classe: z.string(),
    gerant: z.string() }).strict() },                                                                // jamais de rétrogradation auto
  "tache.pms.revue_mandat": { version: 1, schema: z.object({ client: z.string() }).strict() },
  "tache.reevaluation_pep": { version: 1, schema: z.object({ dossier: z.string() }).strict() },      // ADR-PEP-001 : l'humain décide
  "tache.regwatch.analyse": { version: 1, schema: z.object({ empreinte: z.string(), titre: z.string(),
    regles: z.array(z.string()), impact: z.any().nullish(), par: z.string() }).strict() },
  "tache.review.preavis": { version: 1, schema: z.object({ clientId: z.string(),
    dueDate: z.union([z.string(), z.date()]) }).strict() },
  "tache.review.escalade": { version: 1, schema: z.object({ clientId: z.string(),
    dueDate: z.union([z.string(), z.date()]), joursRetard: z.number(), vers: z.string() }).strict() },
  "tache.riskcase.relance": { version: 1, schema: z.object({ statut: z.string() }).strict() },       // jamais d'auto-clôture (R39)
  "task.created": { version: 1, schema: z.object({ origine: z.string(), type: z.string(),
    subjectId: z.string().nullable(), assignee: z.string().nullish() }).strict() },
  "task.created.manual": { version: 1, schema: z.object({ type: z.string(), par: z.string() }).strict() },
  "task.routed": { version: 1, schema: z.object({ role: z.string(), titulaire: z.string().nullish(),
    subjectId: z.string().nullable() }).strict() },
  "task.delegated": { version: 1, schema: z.object({ de: z.string().nullish(), vers: z.string(),
    par: z.string() }).strict() },                                                                   // R38 : de → vers, tracé
  "task.completed": { version: 1, schema: z.object({ acteur: z.string(),
    commentaire: z.string().nullable() }).strict() },                                                // append-only
  "task.sla.retard": { version: 1, schema: z.object({ dueAt: z.union([z.string(), z.date()]).nullable(),
    assignee: z.string().nullish() }).strict() },                                                    // R39 : signal, jamais coercition
  // ── Vague 6 (C6, 2026-08-08) — personne.* (fiche centrale R30→R36, liens R152, CoC/PEP
  //    propagés, ADR-PEP-001 : la dé-PEPisation est une DÉCISION humaine). Payloads RÉELS.
  "personne.creee": { version: 1, schema: z.object({ nom: z.string() }).strict() },
  "personne.creee.minimale": { version: 1, schema: z.object({ nom: z.string(), par: z.string() }).strict() },
  "personne.homonymie.signal": { version: 1, schema: z.object({ nom: z.string(),
    homonymeId: z.string() }).strict() },                                                            // R263 : signal, jamais fusion auto
  "personne.liee": { version: 1, schema: z.object({ dossier: z.string(), role: z.string() }).strict() },
  "personne.role.retire": { version: 1, schema: z.object({ dossier: z.string(), role: z.string() }).strict() },
  "personne.archivee": { version: 1, schema: z.object({ baseLegale: z.string() }).strict() },        // conservation LBA, jamais un effacement
  "personne.reactivee": { version: 1, schema: z.object({}).strict() },
  "personne.flag.pose": { version: 1, schema: z.object({ flag: z.string(), dossier: z.string(),
    cause: z.string() }).strict() },                                                                 // ex. insider par cumul de rôles
  "personne.coc.cree": { version: 1, schema: z.object({ champ: z.string() }).strict() },
  "personne.coc.propage": { version: 1, schema: z.object({ dossier: z.string(), champ: z.string() }).strict() },
  "personne.rescreening.declenche": { version: 1, schema: z.object({ cause: z.string() }).strict() },
  "personne.pep.propage": { version: 1, schema: z.object({ dossier: z.string() }).strict() },        // ADR-PEP-001
  "personne.alerte.depep": { version: 1, schema: z.object({}).strict() },                            // décision humaine ATTENDUE, jamais prise ici
  "personne.relation.declaree": { version: 1, schema: z.object({ b: z.string(), typeAb: z.string(),
    typeBa: z.string() }).strict() },
  "personne.relation.supprimee": { version: 1, schema: z.object({ b: z.string() }).strict() },
  "personne.lien.pose": { version: 1, schema: z.object({ par: z.string(), typeCode: z.string(),
    categorie: z.string(), cibleType: z.string(), cibleId: z.string() }).strict() },                 // R152
  "personne.lien.retrait": { version: 1, schema: z.object({ par: z.string(), typeCode: z.string(),
    motif: z.string() }).strict() },
  "personne.lien.acces.refuse": { version: 1, schema: z.object({ par: z.string(), role: z.string(),
    typeCode: z.string() }).strict() },
  "training.completed": { version: 1, schema: z.object({ userId: z.string(), formationCode: z.string(),
    docId: z.string() }).strict() },
  "training.validated": { version: 1, schema: z.object({ userId: z.string(), formationCode: z.string(),
    par: z.string() }).strict() },
  "training.reminder": { version: 1, schema: z.object({ userId: z.string(), code: z.string(),
    joursRestants: z.number() }).strict() },
  "screening.hit.detecte": { version: 1, schema: z.object({ hitId: z.string(), clientId: z.string(),
    entreeUid: z.string(), score: z.number(), listeVersion: z.string() }).strict() },
  "screening.hit.qualifie": { version: 1, schema: z.object({ hitId: z.string(), verdict: z.string(),
    motif: z.string(), par: z.string() }).strict() },
  "screening.escalade.proposee": { version: 1, schema: z.object({ hitId: z.string(), clientId: z.string(), motif: z.string() }).strict() },
  "pep.proposition.creee": { version: 1, schema: z.object({ cle: z.string(), hitId: z.string(), personId: z.string(),
    liste: z.string(), listeVersion: z.string(), score: z.number(), decomposition: z.any() }).strict() },
  "pep.proposition.rejetee": { version: 1, schema: z.object({ cle: z.string(), motif: z.string(), par: z.string() }).strict() },
  // ── ES-8 : les 4 types consommés par surveillance-es montent au catalogue (fin des gardes
  // locales ES — docs/notes/ES-catalogue-gaps.md soldé). Schémas = payloads RÉELS des émetteurs.
  "tx.flux.importee": { version: 1, schema: z.object({ refExterne: z.string(), source: z.string(),
    compte: z.string(), clientId: z.string().nullish() }).strict() },
  "kyc.validated": { version: 1, schema: z.object({ code: z.string(), validatedBy: z.string() }).strict() },
  // ── Tranche C6 (2026-08-08) : kyc.service quitte les creates DIRECTS — ses 3 types
  // restants passent par emitEvent avec schéma strict (payloads RÉELS des sites d'émission).
  "kyc.created": { version: 1, schema: z.object({ code: z.string(), workflow: z.string(),
    // trace du moteur de risque : entrées STRUCTURÉES (objets) + chaînes appendées (ex. R271) — opaque ici
    riskTrace: z.array(z.any()).nullish() }).strict() },
  "prospect.retour.refuse.detecte": { version: 1, schema: z.object({ code: z.string(),
    dossiersRefuses: z.array(z.string()) }).strict() },
  "kyc.access.modifie": { version: 1, schema: z.object({ question: z.string(), role: z.string(),
    ancienne: z.string(), nouvelle: z.string(), par: z.string(), dateEffet: z.string(),
    portee: z.string(), dossiersTouches: z.number() }).strict() },
  // ── Vague 2 (C6, 2026-08-08) — kyc.* : schémas tirés des payloads réels de kyc.service.ts
  //    et kyc-workflow.chaine.ts (jamais déduits d'une doc). Un champ à deux formes selon le
  //    site d'émission est nullish/optional, jamais élargi en z.any() sans raison de config.
  "kyc.lock.requested": { version: 1, schema: z.object({ code: z.string(), requester: z.string(),
    holder: z.string() }).strict() },
  "kyc.lock.passed": { version: 1, schema: z.object({ code: z.string(), from: z.string(),
    to: z.string() }).strict() },
  "kyc.visa.invalide": { version: 1, schema: z.object({ section: z.string(), cause: z.string(),
    nb: z.number().optional() }).strict() },                         // nb absent au site R21/R22 (par section)
  "kyc.visa.validateur.reassigne": { version: 1, schema: z.object({ section: z.string(),
    requiredRole: z.string(), ancien: z.string().nullable(), nouveau: z.string() }).strict() },
  "kyc.visa.annule.vice": { version: 1, schema: z.object({ section: z.string(),
    requiredRole: z.string(), motif: z.string() }).strict() },
  "kyc.visas.geles": { version: 1, schema: z.object({ hit: z.string(), nb: z.number(),
    delaiAnalyseJours: z.number() }).strict() },                     // R46
  "kyc.comite.decision": { version: 1, schema: z.object({ hit: z.string(),
    decision: z.enum(["poursuite", "offboarding"]), membres: z.array(z.string()) }).strict() },   // R46
  "kyc.offboarding.propose": { version: 1, schema: z.object({ hit: z.string(),
    origine: z.string() }).strict() },                               // R44 : propose, ne décide jamais
  "kyc.dossier.suspendu": { version: 1, schema: z.object({ cause: z.string(),
    restrictions: z.record(z.any()).optional() }).strict() },        // restrictions = JSON tenant (R-Q), figé à date (S-09)
  "kyc.dossier.reactive": { version: 1, schema: z.object({}).strict() },
  "kyc.dossier.abandonne": { version: 1, schema: z.object({ motif: z.string() }).strict() },
  "kyc.dossier.mise_a_jour": { version: 1, schema: z.object({ description: z.string(),
    sections: z.array(z.string()) }).strict() },                     // R21/R22 : réouverture ciblée
  "kyc.effacement.refuse.lba": { version: 1, schema: z.object({ demandeur: z.string(),
    baseLegale: z.string() }).strict() },
  "kyc.process.ouvert": { version: 1, schema: z.object({ process: z.string(), type: z.string() }).strict() },
  "kyc.process.pause": { version: 1, schema: z.object({ cause: z.string(), nb: z.number() }).strict() },
  "kyc.process.repris": { version: 1, schema: z.object({ process: z.string(),
    sectionsAbsorbees: z.array(z.string()) }).strict() },
  "kyc.process.cloture": { version: 1, schema: z.object({ process: z.string(),
    sections: z.array(z.string()) }).strict() },
  "kyc.dossier.workflow": { version: 1, schema: z.object({ source: z.enum(["GOUVERNE", "TEMPLATE"]),
    workflowCode: z.string(), version: z.number().nullable(), depuisLe: z.string().nullable() }).strict() },   // R172 : le timbre
  "personne.pep.declare": { version: 1, schema: z.object({ source: z.string(), sourceHitId: z.string().nullish() }).strict() },
  "personne.pep.leve": { version: 1, schema: z.object({ decideur: z.string(), sourceHitId: z.string().nullish() }).strict() },
  // ── Bloc WD (R432/R436) : WorkflowIR — source → brut → éditions → visa, rejouable ──
  "wd.wir.importe": { version: 1, schema: z.object({ documentId: z.string(), hash: z.string(),
    modele: z.string(), wir: z.any(), zonesIllisibles: z.any() }).strict() },
  "wd.wir.edite": { version: 1, schema: z.object({ patch: z.object({ noeud: z.string(),
    label: z.string().optional(), ownerRole: z.string().optional(), slaHours: z.number().optional() }).strict(),
    par: z.string() }).strict() },
  "wd.wir.ratifie": { version: 1, schema: z.object({ par: z.string(), defId: z.string() }).strict() },
  // ── Bloc 62 — offboarding AU MOTEUR (repo R439–R445) : l'état est un REJEU de ces événements ──
  "WORKFLOW_STARTED": { version: 1, schema: z.object({ clientId: z.string(), motif: z.string(),
    par: z.string(), role: z.string(), niveau: z.string(), origineNiveau: z.string(),
    chaine: z.array(z.string()), checklist: z.array(z.object({ label: z.string(), obligatoire: z.boolean() })),
    guards: z.record(z.string()), dateInitiation: z.string() }).strict() },
  "TRANSITION_FIRED": { version: 1, schema: z.object({ from: z.string(), to: z.string(),
    visa: z.object({ validateur: z.string(), role: z.string(), at: z.string() }).strict().nullish() }).strict() },
  "VISA_APPOSE": { version: 1, schema: z.object({ validateur: z.string(), role: z.string(),
    at: z.string(), maillon: z.number() }).strict() },          // multi-visas R1 sur la clôture (chaînes > 3)
  "GUARD_BLOCKED": { version: 1, schema: z.object({ guard: z.string(), reason: z.string(),
    etape: z.string() }).strict() },
  "GUARD_WARNING": { version: 1, schema: z.object({ guard: z.string(), reason: z.string(),
    etape: z.string() }).strict() },
  "WORKFLOW_COMPLETED": { version: 1, schema: z.object({ par: z.string() }).strict() },
  "CHECKLIST_ITEM_CHECKED": { version: 1, schema: z.object({ label: z.string(), par: z.string() }).strict() },
  "PARAM_CHANGED": { version: 1, schema: z.object({ cle: z.string(), ancien: z.any(), nouveau: z.any(),
    enVigueurLe: z.string(), auteur: z.string(), engagementTexte: z.string(), portee: z.string() }).strict() },
  // ── Ingestion de listes versionnée (R409 · L6) ──
  "liste.version.importee":  { version: 1, schema: z.object({ source: z.string(), version: z.string(), hash: z.string(),
    nEntrees: z.number(), ajoutees: z.number(), modifiees: z.number(), retirees: z.number() }).strict() },
  "liste.rescreening.cible": { version: 1, schema: z.object({ source: z.string(), version: z.string(),
    entrees: z.number(), hits: z.number() }).strict() },
  "liste.delisting.revue":   { version: 1, schema: z.object({ source: z.string(), version: z.string(),
    uid: z.string(), hitId: z.string() }).strict() },
};

// ── Types EN ATTENTE de schéma (inventaire des littéraux émis — migration douce, à réduire) ──
export const TYPES_EN_ATTENTE: ReadonlySet<string> = new Set([
  "ACTE_DECES",
  "ADDRESS_CHANGE",
  "AIGUILLAGE_EDD",
  "AI_DECIDE",
  "AI_QUERY",
  "AJUSTEMENT_PARAM",
  "ALLEGEMENT_EDD",
  "AMI_PROCHE_DE",
  "AML_ANNUELLE",
  "AML_BTL_CAMPAGNE",
  "AML_CALIBRAGE_ANNUEL",
  "AML_DQ_CONTROLE",
  "AML_EVALUATED",
  "AML_EVAL_BACKTEST",
  "AML_EVAL_CLIENT",
  "AML_EVAL_DRAIN",
  "AML_EVAL_VERSION",
  "AML_GAP_GT_SEED",
  "AML_GAP_QUALIFY",
  "AML_GAP_SIGNAL",
  "ASSOCIE_DE",
  "AUCUN_CHECK",
  "AUDIT_ACCESS",
  "AUDIT_EXPORT",
  "AUDIT_HMAC_SECRET",
  "BLOQUANT_APPROBATION",
  "BLOQUEE_REVUE",
  "BREAK_GLASS_LOGIN",
  "BUDGET_TICK",
  "BUILDER_PUBLISH",
  "CERTIFICATION_EXPIRED_AT_TRIP_DATE",
  "CERTIFICATION_ISSUED",
  "CHAMPS_OBLIGATOIRES",
  "CLIENTS_PRODUITS_PRATIQUES",
  "CLIENT_CREATED",
  "CLOTURE_ANNULEE",
  "CLOTURE_DEMANDEE",
  "COC_CONFIG_DEFINIE",
  "COC_EN_TRAITEMENT",
  "COC_NON_RETENU",
  "COC_OUVERT",
  "COC_SIGNAL_NON_EMIS",
  "COC_TRAITE",
  "COC_TRAITEMENT_DEMANDE",
  "COFFRE_INTERNE",
  "CONSEILLER_EXTERNE",
  "CONSEIL_FONDATION",
  "CONVERSION_CRYPTO",
  "CORE_RESOLVE",
  "CORE_SYNC",
  "CO_SR",
  "CO_TITULAIRE",
  "CPSI_CASE_PROPOSAL_EMITTED",
  "CPSI_CLIENT_ALREADY_REGISTERED",
  "CPSI_CLIENT_REGISTERED",
  "CPSI_GROUP_DEFINED",
  "CPSI_PARAM_APPLIED",
  "CPSI_REPLAY_SLOW",
  "CPSI_RULES",
  "CPSI_SCENARIO_DEFINED",
  "CPSI_SCORE",
  "CPSI_SIGNAL_INGESTED",
  "CPSI_SLA_TICK",
  "CRASH_TEST",
  "CRM_CONTACT",
  "CROSS_BORDER_AE",
  "DECES_SUCCESSION",
  "DECISION_BANQUE",
  "DEMANDE_CLIENT",
  "DETENTEUR_CONTROLE",
  "DOMMAGES_ACTIFS",
  "EN_ANALYSE",
  "EN_ATTENTE",
  "EN_CLOTURE",
  "EN_COURS",
  "EN_MAJ",
  "EN_PAUSE",
  "EN_RETARD",
  "EN_TRAITEMENT",
  "EN_VIGUEUR",
  "EPOUX_DE",
  "ETAPE_AGENT",
  "ETAPE_OUTIL",
  "EXECUTION_PROCESSUS",
  "EXIT_COMPLIANCE",
  "EXPIRATION_FUTURE",
  "FAUX_POSITIF",
  "FF_RLS_ENFORCED",
  "FILS_FILLE_DE",
  "FORM_CDB",
  "FRAUDE_EXTERNE",
  "FRAUDE_INTERNE",
  "FRERE_SOEUR_DE",
  "GED_ANCHORED",
  "GED_ARCHIVED",
  "GED_CLASSIFIED",
  "GED_CLASSIFY",
  "GED_CONSULT_FICHE",
  "GED_DESTROYED",
  "GED_HOLD_LIFTED",
  "GED_INGEST",
  "GED_QES",
  "GED_READ",
  "GED_VERSION_CREATED",
  "IA_PREREVIEW",
  "IA_PROMPT_VERSIONED",
  "IA_VALIDEE",
  "IDENTITY_DIVERGENCE",
  "INSTRUCTION_TRANSFERT_SIGNEE",
  "INTERRUPTION_SYSTEMES",
  "IN_PROGRESS",
  "ISLAMIC_EVALUATED",
  "KYC_ACCESS_MODIFIE",
  "KYC_CREATED",
  "KYC_ENGAGEMENT_RESPONSABILITE",
  "KYC_EN_COURS",
  "KYC_FILE",
  "KYC_NOT_APPROVED",
  "KYC_QUESTION",
  "KYC_REVOCATION_REFUSEE",
  "KYC_SECTION",
  "KYC_VALIDATED",
  "KYC_VALIDATION",
  "KYC_VISA",
  "KYC_VISA_SIGNED",
  "LEGAL_OBJET_CREE",
  "LICENCE_CHARGEE",
  "LICENSE_ISSUED",
  "MAJ_CIBLEE",
  "MERE_DE",
  "MFA_ENC_KEY",
  "MOBILE_IDENTITE_CREEE",
  "MOBILE_MESSAGE_BANQUE",
  "MOBILE_PARTAGE_MARQUE",
  "MROS_DECISION",
  "MROS_FREEZE_LIFTED",
  "MROS_FREEZE_SET",
  "NBA_ADJUSTMENT_REQUIRED",
  "NBA_ALREADY_DECIDED",
  "NBA_DECIDED",
  "NBA_DECISION_HUMAN_ONLY",
  "NBA_REJECT_RATIONALE_REQUIRED",
  "NEAR_MISS",
  "NEVEU_NIECE_DE",
  "NE_PAS_COMMUNIQUER",
  "NON_DETERMINE",
  "NON_OFFICIEL",
  "NON_PERTINENT",
  "NON_QUALIFIEE",
  "NON_RETENU",
  "NON_TRAITE",
  "NON_TRANSMISSION",
  "OCR_ACCEPT",
  "OCR_EXTRACTION",
  "OFFBOARDING_ATTESTATION_AVOIRS",
  "OFFBOARDING_DEMANDE",
  "OFFBOARDING_TRANSITION",
  "OFFBOARDING_VISA",
  "OLIVIA_AGENT_DECLARED",
  "OLIVIA_AGENT_RETIRED",
  "OLIVIA_CONTEXT_DENIED",
  "OLIVIA_CONVERSATION_CREATED",
  "OLIVIA_CONVERSATION_FERMEE",
  "OLIVIA_FEEDBACK",
  "OLIVIA_INJECTION_SUSPECTEE",
  "OLIVIA_MESSAGE",
  "OLIVIA_MESSAGE_IN",
  "OLIVIA_MESSAGE_OUT",
  "OLIVIA_PROPOSAL_ADOPTED",
  "OLIVIA_PROPOSAL_CADUQUE",
  "OLIVIA_PROPOSAL_CREATED",
  "OLIVIA_PROPOSAL_REJECTED",
  "OLIVIA_RUN_EPUISE",
  "OLIVIA_RUN_GATE",
  "OLIVIA_RUN_INTERROMPU",
  "OLIVIA_RUN_PORTE",
  "OLIVIA_RUN_PORTE_EXPIREE",
  "OLIVIA_RUN_REPLAY",
  "OLIVIA_RUN_STOP",
  "OLIVIA_RUN_TERMINE",
  "OLIVIA_SCOPE_DENIED",
  "OLIVIA_TOOL_DECLARED",
  "ONBOARDING_CREATED",
  "ONBOARDING_TRANSITION",
  "ONCLE_TANTE_DE",
  "OPRISK_INCIDENT_DECLARE",
  "OPRISK_INCIDENT_TRANSITION",
  "PAUSE_PORTE",
  "PENDING_APPROVAL",
  "PEP_LIFTED",
  "PEP_PROPOSITION",
  "PEP_PROPOSITION_REJECTED",
  "PEP_STATUS",
  "PERE_DE",
  "PERSON_COC",
  "PERSON_CREATED",
  "PERSON_LINK",
  "PMS_BREACH_CLOSED",
  "PMS_PRETRADE_BLOCK",
  "PMS_VALUATION",
  "PORTE_DECISION",
  "PORTE_OUVERTE",
  "POSITION_SANS_REGISTRE",
  "POWER_OF_ATTORNEY",
  "POWER_OF_INFORMATION",
  "PRATIQUES_EMPLOI",
  "PREAVIS_OUVERT",
  "PRISE_CONNAISSANCE",
  "QUALIF_ALERTE",
  "QUANTITES_DIVERGENTES",
  "RECO_PROSE_TEST",
  "REGISTRE_SANS_POSITION",
  "REGWATCH_COLLECTE",
  "REGWATCH_QUALIFIE",
  "REVIEW_ANTICIPEE",
  "REVIEW_DEADLINE_ANTICIPEE",
  "REVIEW_DEADLINE_REALISEE",
  "REVIEW_DEADLINE_REPORTEE",
  "REVIEW_DEADLINE_REPORT_DEMANDE",
  "REVIEW_DEADLINE_SET",
  "REVIEW_LANCEE",
  "REVIEW_RECALCUL",
  "REVIEW_REPORTEE",
  "REVIEW_SECTION_CONFIRMEE",
  "REVISION_KYC",
  "RISKCASE_FROM_PROPOSAL",
  "RISKCASE_OPENED",
  "RISKCASE_TRANSITION",
  "RISK_CASE",
  "SANS_ECHEANCE",
  "SCOPE_DENIED",
  "SCREENING_CONFIG_PUBLIEE",
  "SCREENING_EXPORT",
  "SCREENING_QUALIFIED",
  "SCREENING_REPLAY",
  "SCREENING_RUN",
  "SSO_FALLBACK_LOCAL_UTILISE",
  "SSO_JWKS_ROTATION",
  "SSO_MODE_BASCULE",
  "SSO_TEST",
  "STREAM_INTERROMPU_TEST",
  "SWIFT_PARSE",
  "SWIFT_QUARANTAINE",
  "TASK_ALREADY_COMPLETED",
  "TASK_COMPLETED",
  "TASK_COMPLETE_FORBIDDEN",
  "TASK_CREATED",
  "TASK_CREATED_MANUAL",
  "TASK_DELEGATED",
  "TASK_MANUAL_CREATION_DISABLED",
  "TASK_ROUTED",
  "TA_CONTREPASSATION",
  "TA_ECART_RESOLU",
  "TA_MOUVEMENT",
  "TA_VISA",
  "TENANT_ACTIVATED",
  "TIMEOUT_TEST",
  "TRAINING_ASSIGNED",
  "TRAINING_COMPLETED",
  "TRAINING_SELF_VALIDATION_FORBIDDEN",
  "TRAINING_VALIDATED",
  "TRANSFERT_ETABLISSEMENT",
  "TRANSMISSION_AUTORITE",
  "TRANSPORT_DEADLETTER_REJOUEE",
  "TRIP_KYC_NOT_APPROVED",
  "TRIP_REVISED",
  "TRIP_SELF_APPROVAL_FORBIDDEN",
  "TRIP_SUBMITTED",
  "TRIP_VISA",
  "TXFLUX_IMPORT",
  "TX_GATE",
  "TX_REVIEW",
  "UBO_CHANGE",
  "UNDER_REVIEW",
  "VAULT_CERTIFIED_PURGE",
  "VAULT_WRITE",
  "VIEW_CREATE",
  "VRAI_POSITIF",
  "WORKFLOW_PUBLISH",
  "WORKLOAD_REASSIGN",
  "XB_DEROGATION_DEMANDEE",
  "XB_DEROGATION_VISEE",
  "XB_ORDRE_ENREGISTRE",
  "annotation.acces.refuse",
  "annotation.posee",
  "annotation.retiree",
  "auth.breakglass.utilise",
  "builder.publication",
  "builder.simulation",
  "cablage.caviarde.depose",
  "caviardage.produit",
  "caviardage.refuse",
  "central_file.dossier.ouvert",
  "client.coc",
  "coffre.ecrit",
  "coffre.integrite.alerte",
  "coffre.purge.certifiee",
  "coffre.reconciliation.manquant",
  "coffre.reconciliation.orphelin",
  "core.acces.refuse",
  "core.sync.lot",
  "core.sync.quarantaine",
  "core.sync.resolution",
  "cpsi.client.registered",
  "cpsi.fp.declared",
  "cpsi.group.defined",
  "cpsi.insider.lifted",
  "cpsi.insider.tagged",
  "cpsi.param.adopted",
  "cpsi.param.applied",
  "cpsi.param.proposed",
  "cpsi.param.rejected",
  "cpsi.scenario.defined",
  "cpsi.signal.ingested",
  "crm.acces.refuse",
  "crm.contact.cree",
  "deploiement.enregistre",
  "divulgation.executee",
  "divulgation.refusee",
  "dq.degraded",
  "fake-1.0",
  "fx.seuil.franchi",
  "gwb-private.ch",
  "gwb.ch",
  "ia.acces.refuse",
  "ia.decision",
  "ia.ecart",
  "ia.point.ecarte",
  "ia.point.traite",
  "ia.prerevue.produite",
  "ia.production",
  "ia.prompt.versionne",
  "ia.proposition",
  "iam.cumul_so_admin.autorise",
  "islamic.audit.shariah",
  "islamic.mudaraba.distribue",
  "islamic.operation.bloquee",
  "islamic.qard.suivi",
  "islamic.signal.leve",
  "islamic.sukuk.maturite",
  "islamic.takaful.suivi",
  "islamic.waqf.distribue",
  "islamic.zakat.calcule",
  "legal.echeance.escalade",
  "legal.objet.cree",
  "legal.objet.dates",
  "licence.expiration.j30",
  "licence.expiration.j60",
  "licence.expiree",
  "matrice_documentaire.publiee",
  "mobile.identite.activee",
  "mobile.identite.creee",
  "mobile.message",
  "mobile.message.traite",
  "mobile.partage.marque",
  "mobile.session.ouverte",
  "module.licence.chargee",
  "nba.decided",
  "notification",
  "ocr.controle.echec",
  "ocr.extraction.produite",
  "ocr.proposition.acceptee",
  "ocr.proposition.creee",
  "ocr.proposition.refusee",
  "offboarding.attestation_avoirs",
  "offboarding.demande",
  "offboarding.document",
  "offboarding.transition",
  "offboarding.visa",
  "olivia.agent.declare",
  "olivia.agent.retire",
  "olivia.outil.declare",
  "olivia.run.porte",
  "olivia.run.porte.expiree",
  "olivia.runs.saturation",
  "onboarding.cree",
  "onboarding.kyc.cree",
  "onboarding.ouvert",
  "onboarding.sla.alerte",
  "onboarding.transition",
  "oprisk.action.creee",
  "oprisk.action.escalade",
  "oprisk.action.statut",
  "oprisk.incident.declare",
  "oprisk.incident.transition",
  "pacs.008",
  "param.change",
  "param.effet.applique",
  "pms.breach.clos",
  "pms.breach.escalade",
  "pms.drift.detecte",
  "pms.mandat.attache",
  "pms.pretrade.bloque",
  "pms.pretrade.ok",
  "pms.suitability.alerte",
  "recherche.executee",
  "recherche.index.desync",
  "recherche.index.entree",
  "recherche.index.retrait",
  "regwatch.digest",
  "regwatch.fetch",
  "regwatch.item",
  "regwatch.proposition",
  "regwatch.qualification",
  "review.changement.signale",
  "review.lancee",
  "review.section.confirmee",
  "rh.bonification.snapshot",
  "riskcase.note",
  "riskcase.ouvert",
  "riskcase.signal.detache",
  "riskcase.signal.rattache",
  "riskcase.sla.alerte",
  "riskcase.transition",
  "risque.operationnel.incident",
  "signal.aml.comportement",
  "sso.jwks.rotation",
  "sso.mode.bascule_demandee",
  "sso.mode.bascule_visee",
  "sso.test",
  "swift.message.parse",
  "swift.quarantaine",
  "ta.contrepassation",
  "ta.ecart.resolu",
  "ta.mouvement.enregistre",
  "ta.mouvement.vise",
  "ta.rapprochement",
  "tenant.active",
  "transport.deadletter",
  "transport.deadletter.rejouee",
  "tuning.btl.campagne",
  "tuning.calibrage.annuel",
  "tx.revue.acces.refuse",
  "tx.revue.decision",
  "tx.revue.sla",
  "tx.suspend",
  "tx.verdict",
  "vendor.licence.acces.refuse",
  "vendor.licence.emise",
  "workflow.def.acces.refuse",
  "workflow.def.brouillon",
  "workflow.def.publiee",
  "workload.acces.refuse",
  "workload.surcharge.signalee",
  "workload.tache.reassignee",
  "xb.check",
  "xb.derogation.demandee",
  "xb.derogation.visee",
  "xb.ordre.enregistre",
]);

export const versionDe = (type: string): number => SCHEMAS_EVENEMENTS[type]?.version ?? 1;
