# -*- coding: utf-8 -*-
# WAVE 2 — blocs 57-61 (R378-R403 provisoires) — chargé par gen_aml_gap.py (exec)
WAVE2 = [
# ══ BLOC 57 — TBML (R378-R385) ══
R("TB-01","R378","TBML","Surfacturation (over-invoicing)","🧾",2,False,
  "Factures systématiquement payées au-dessus de la valeur de marché des biens — miroir sortant de R201 : la survaleur transfère du blanchiment sous couvert commercial.",
  "8 paiements de factures d'import présentent un écart constant de +22% vs le prix de référence des biens (code HS).",
  "Écart récurrent ≥ seuil entre montant payé et valeur de référence, sur ≥ N factures / 90j.",
  "Signal OVER_INVOICING (Niveau 2) — analyse trade finance, justificatifs contractuels et incoterms demandés.",
  [["ecart_prix_seuil","écart au prix de référence","15","%"],["nb_factures_min","factures concernées / 90j","3","-"]],
  [TP("CLI-00130","Import de composants payés +22% vs benchmark sur 8 factures du même fournisseur lié — transfert de valeur confirmé."),
   FP("CLI-00101","Surcoût de +18% documenté par une clause d'urgence logistique (fret aérien vs maritime, contrat fourni) — FP.")]),
R("TB-02","R379","TBML","Facturation multiple","🔁",2,False,
  "Le même bien ou la même expédition est facturé et payé plusieurs fois, via un ou plusieurs financeurs.",
  "Deux paiements de CHF 140k référencent le même connaissement (B/L) à 3 semaines d'écart.",
  "Déduplication des références documentaires (B/L, facture, conteneur) sur les paiements trade / 180j.",
  "Signal MULTIPLE_INVOICING (Niveau 2) — documents originaux exigés, vérification auprès du transporteur.",
  [["fenetre_dedup","fenêtre de déduplication","180","jours"]],
  [TP("CLI-00130","Même connaissement financé deux fois via deux banques — double financement frauduleux confirmé."),
   FP("CLI-00193","Facture d'acompte puis facture de solde portant la même référence commande (schéma 30/70 contractuel) — FP.")]),
R("TB-03","R380","TBML","Prix hors benchmark (unit price)","📐",2,False,
  "Analyse du prix unitaire par code HS contre des référentiels de prix de marché — les écarts extrêmes signent la mis-invoicing.",
  "Des « composants électroniques » sont facturés CHF 2 pièce alors que le référentiel HS donne 40-60.",
  "Prix unitaire vs distribution de référence du code HS ; écart au-delà des percentiles paramétrés.",
  "Signal UNIT_PRICE_ANOMALY (Niveau 2) — nature réelle des biens à corroborer.",
  [["percentile_bas","percentile bas","5","%"],["percentile_haut","percentile haut","95","%"],["referentiel_hs","référentiel de prix HS","tenant","-"]],
  [TP("CLI-00130","Biens sous-facturés à 5% du prix de marché pour exfiltrer de la valeur au pays d'origine — TP."),
   FP("CLI-00037","Lot déclassé vendu à prix cassé avec certificat de non-conformité joint — décote documentée, FP.")]),
R("TB-04","R381","TBML","Biens à double usage","☢",1,False,
  "Paiements liés à des biens à double usage (annexes du contrôle des exportations) vers des destinations sensibles.",
  "Un paiement finance des machines-outils de précision classées double usage vers un intermédiaire au pays tiers.",
  "Classification des biens (HS + libellés) croisée avec les listes de contrôle des exportations et la destination finale.",
  "Signal DUAL_USE (Niveau 1) — licence d'exportation SECO à exiger avant exécution, escalade sanctions.",
  [["listes_controle","listes de contrôle actives","SECO,EU","-"]],
  [TP("CLI-00039","Machines classées double usage routées via un intermédiaire vers une destination sous embargo — licence absente, TP."),
   FP("CLI-00142","Bien listé mais licence d'exportation SECO valide fournie et destinataire final vérifié — conforme, FP.")]),
R("TB-05","R382","TBML","LC back-to-back / crédits doc HRJ","🔗",2,False,
  "Lettres de crédit adossées (back-to-back) ou crédits documentaires dont la chaîne implique des juridictions à risque sans logique commerciale.",
  "Une LC est adossée à une seconde LC émise pour un intermédiaire offshore qui ne touche jamais la marchandise.",
  "Détection de LC adossées × intermédiaires sans rôle logistique × juridictions de la chaîne.",
  "Signal BACK_TO_BACK_LC (Niveau 2) — substance de l'intermédiaire à démontrer.",
  [["hrj_trade","liste juridictions trade à risque","tenant","-"]],
  [TP("CLI-00043","Intermédiaire des Caïmans intercalé entre acheteur et vendeur réels, marge de 12% sans fonction — écran, TP."),
   FP("CLI-00150","Maison de négoce établie jouant un rôle réel de contrepartie centrale (contrats et assurances au dossier) — FP.")]),
R("TB-06","R383","TBML","Phantom shipping","👻",1,False,
  "Paiement sans mouvement de marchandise vérifiable : documents absents, navires inexistants, conteneurs fantômes.",
  "Un paiement de CHF 380k référence un conteneur dont le tracking ne montre aucun mouvement.",
  "Vérification d'existence du voyage (API tracking conteneurs/navires) pour les paiements trade ≥ seuil.",
  "Signal PHANTOM_SHIPMENT (Niveau 1) — fonds gelés en attente de preuve d'expédition, EDD.",
  [["seuil_verif_tracking","seuil de vérification","100000","CHF"]],
  [TP("CLI-00130","Trois « expéditions » payées 1.1M au total, aucun conteneur n'a jamais quitté le port déclaré — TP."),
   FP("CLI-00193","Retard de mise à jour du tracking d'un transporteur secondaire (mouvement confirmé à J+4 par le B/L) — FP.")]),
R("TB-07","R384","TBML","Routes & transbordements atypiques","🗺",2,False,
  "Routes maritimes incohérentes avec la géographie commerciale : détours, transbordements multiples, pavillons changés en cours de voyage.",
  "Une cargaison Rotterdam→Genève transite par 3 ports hors route avec 2 transbordements.",
  "Score d'anomalie de route (détour, transbordements, arrêts en zones sensibles) sur les documents de transport.",
  "Signal ROUTE_ANOMALY (Niveau 2) — justification logistique demandée.",
  [["transbordements_max","transbordements tolérés","1","-"]],
  [TP("CLI-00039","Détour par un port connu pour le maquillage d'origine (certificats réémis) — contournement d'embargo, TP."),
   FP("CLI-00150","Réacheminement dû à une congestion portuaire majeure documentée par l'armateur (avis publié) — FP.")]),
R("TB-08","R385","TBML","Carrousel documentaire","🎠",2,False,
  "Les mêmes contreparties échangent des rôles acheteur/vendeur sur des biens similaires en boucle — chiffre d'affaires artificiel.",
  "A vend à B, B revend à C, C revend à A des lots similaires à valeur croissante sur 4 mois.",
  "Détection de cycles sur le graphe des contreparties trade × similarité des biens × inflation des montants.",
  "Signal TRADE_CAROUSEL (Niveau 2) — logique économique de la chaîne à démontrer.",
  [["duree_cycle_trade","fenêtre de détection","180","jours"]],
  [TP("CLI-00101","Boucle de revente à valeur +15% par tour entre trois entités liées au même bénéficiaire — carrousel confirmé."),
   FP("CLI-00037","Négoce légitime de matières premières où les rôles s'inversent selon les cours (positions documentées) — FP.")]),

# ══ BLOC 58 — CORRESPONDENT BANKING (R386-R392) ══
R("CB-03","R386","Correspondent Banking","Wire stripping / transparence","✂",1,False,
  "Champs ordonnateur/bénéficiaire (50/59) incomplets, tronqués ou altérés dans la chaîne — GAFI R.16, Wolfsberg Payment Transparency.",
  "Une série de MT103 d'un correspondant arrive avec le champ 50 réduit à des initiales.",
  "Contrôle de complétude et de cohérence des champs de transparence par message et par correspondant (taux agrégé).",
  "Signal WIRE_STRIPPING (Niveau 1) — messages retenus, demande de complément au correspondant, taux suivi par répondant.",
  [["taux_incomplet_max","taux d'incomplétude toléré par correspondant","2","%"]],
  [TP("CLI-00130","Correspondant supprimant systématiquement le nom d'ordonnateurs iraniens (initiales seules) — stripping confirmé, relation revue."),
   FP("CLI-00018","Troncature technique de caractères non-latins par un système legacy (données complètes en pièce jointe MT199) — FP, correctif demandé.")]),
R("CB-04","R387","Correspondent Banking","U-turn payments","↩",2,False,
  "Fonds sortant vers un correspondant tiers et revenant à la même partie via une autre chaîne — contournement de restrictions.",
  "CHF 500k partent vers une banque du Golfe et reviennent 9 jours après via un correspondant européen, même bénéficiaire final.",
  "Appariement sortie/entrée (montant, parties finales, fenêtre) à travers des chaînes de correspondance distinctes.",
  "Signal U_TURN (Niveau 2) — finalité du détour à justifier, analyse sanctions.",
  [["fenetre_uturn","fenêtre d'appariement","30","jours"]],
  [TP("CLI-00070","Détour par deux correspondants pour masquer une contrepartie russe restreinte — contournement confirmé."),
   FP("CLI-00164","Paiement rejeté par la banque bénéficiaire (IBAN erroné) et retourné par une autre route — retour technique documenté, FP.")]),
R("CB-05","R388","Correspondent Banking","Payable-through accounts","🚇",1,False,
  "Clients du répondant accédant directement au compte de correspondance (payable-through) — diligence impossible sur l'utilisateur final.",
  "Des ordres au format client final (références retail) transitent par le compte nostro d'un répondant.",
  "Détection de patterns d'usage direct (volumétrie retail, références client final) sur comptes de correspondance.",
  "Signal PAYABLE_THROUGH (Niveau 1) — clarification contractuelle avec le répondant, restriction possible après décision.",
  [["indicateurs_pta","indicateurs d'usage direct","tenant","-"]],
  [TP("CLI-00130","Répondant offrant à ses clients un accès quasi direct au nostro (milliers de micro-ordres) — PTA confirmé, convention résiliée."),
   FP("CLI-00018","Pic de petits ordres dû à une migration de paie groupée du répondant (préavisée par MT199) — usage propre, FP.")]),
R("CB-06","R389","Correspondent Banking","Volumétrie répondant vs profil (KYCC)","📊",2,False,
  "Volumes et corridors d'un répondant incohérents avec son profil déclaré (questionnaire Wolfsberg CBDDQ).",
  "Un répondant déclaré « domestique retail » envoie 40% de ses flux vers des corridors HRJ.",
  "Comparaison flux réels (corridors, volumes, devises) vs profil CBDDQ déclaré, par période.",
  "Signal RESPONDENT_PROFILE_DRIFT (Niveau 2) — mise à jour du questionnaire exigée, revue de la relation.",
  [["derive_max","dérive tolérée vs profil","20","%"]],
  [TP("CLI-00130","Répondant « retail domestique » devenu hub régional de flux vers zones grises sans mise à jour CBDDQ — dérive confirmée."),
   FP("CLI-00150","Croissance de corridor liée à l'acquisition documentée d'une banque voisine (communiqué + CBDDQ mis à jour) — FP.")]),
R("CB-07","R390","Correspondent Banking","Shell bank","🐚",1,True,
  "Détection de banques fictives (sans présence physique ni groupe régulé) dans les chaînes — interdiction LBA.",
  "Un BIC de la chaîne appartient à un établissement sans adresse physique vérifiable ni superviseur identifiable.",
  "Croisement BIC × registres de supervision × indicateurs de présence physique (référentiel tenant).",
  "TRANSACTION BLOQUÉE (Niveau 1) — interdiction légale, aucune dérogation, dossier sanctions/MROS selon le cas.",
  [["registres_supervision","registres de superviseurs consultés","tenant","-"]],
  [TP("CLI-00043","Établissement caribéen sans licence vérifiable ni locaux (adresse = boîte postale d'un agent) — shell bank, blocage."),
   FP("CLI-00164","Banque digitale licenciée sans agences mais dûment supervisée (registre du régulateur consulté) — présence légale établie, FP.")]),
R("CB-08","R391","Correspondent Banking","RMA sans flux ni justification","🔌",1,False,
  "Autorisations d'échange SWIFT (RMA) actives sans flux ni besoin documenté — surface d'attaque et de contournement inutile.",
  "Un RMA bilatéral est actif depuis 3 ans avec zéro message échangé.",
  "Revue périodique des RMA : flux sur la période × justification métier enregistrée.",
  "Signal RMA_DORMANT (Niveau 1, ops) — proposition de résiliation, décision tracée.",
  [["periode_revue_rma","période de revue","12","mois"]],
  [TP("CLI-00130","RMA dormant réactivé soudainement pour une série de MT202 vers une zone grise — le canal oublié servait de porte dérobée."),
   FP("CLI-00018","RMA maintenu par exigence contractuelle d'un schéma de garantie multilatéral (convention au dossier) — justifié, FP.")]),
R("CB-09","R392","Correspondent Banking","Screening des répondantes (CBDDQ)","🛰",2,False,
  "Screening périodique des banques répondantes elles-mêmes : sanctions, adverse media, rating pays, actionnariat.",
  "L'actionnaire majoritaire d'un répondant est placé sous sanctions.",
  "Re-screening périodique du répondant + UBO bancaires + dirigeants ; delta → revue.",
  "Signal RESPONDENT_HIT (Niveau 2) — comité correspondance, suspension possible après décision humaine.",
  [["frequence_screen_respondants","fréquence","30","jours"]],
  [TP("CLI-00130","Nouvel actionnaire de contrôle d'un répondant apparu sur liste de sanctions — relation suspendue après comité."),
   FP("CLI-00150","Adverse media visant l'homonyme d'une autre banque du même groupe de presse — établissement distinct, FP.")]),

# ══ BLOC 59 — PROLIFÉRATION (R393-R395) ══
R("PF-01","R393","Prolifération","Sanctions sectorielles & plafonds","🛢",1,True,
  "Contournement des sanctions sectorielles : plafonds de prix (pétrole), embargos or/luxe, services interdits (assurance, shipping) vers RU/BY/IR/KP.",
  "Un paiement pétrole affiche un prix au baril supérieur au plafond, assuré par un assureur non autorisé.",
  "Contrôle sectoriel : produit × origine × prix vs plafond × services associés autorisés.",
  "TRANSACTION BLOQUÉE (Niveau 1) — violation sectorielle, escalade sanctions, décision humaine tracée.",
  [["plafonds_sectoriels","référentiel plafonds/embargos","tenant","-"]],
  [TP("CLI-00039","Cargaison d'origine russe payée au-dessus du price cap via un négociant intermédiaire — violation confirmée, blocage."),
   FP("CLI-00037","Pétrole d'origine certifiée kazakhe transitant par un port russe (certificat d'origine et pipeline documentés) — hors périmètre du plafond, FP.")]),
R("PF-02","R394","Prolifération","Chaînes d'écrans corridors KP/IR","🕸",1,False,
  "Patterns d'intermédiation typiques du financement de la prolifération : sociétés jeunes, capital minimal, secteurs génériques, en chaîne vers corridors sensibles.",
  "Trois sociétés de trading créées < 12 mois s'intercalent entre un exportateur européen et un acheteur final opaque.",
  "Score de chaîne : âge des entités × substance × secteur générique × corridor final.",
  "Signal PROLIF_CHAIN (Niveau 1) — identification du destinataire final exigée, escalade.",
  [["age_entite_min","âge minimal sans surrisque","24","mois"]],
  [TP("CLI-00043","Chaîne de trois écrans hongkongais récents aboutissant à une entité liée à un programme sous sanctions — TP."),
   FP("CLI-00045","Jeunes filiales de distribution d'un groupe industriel établi (organigramme et comptes consolidés fournis) — substance démontrée, FP.")]),
R("PF-03","R395","Prolifération","Biens de luxe vers zones embargo","💎",2,False,
  "Exportation de biens de luxe (montres, joaillerie, véhicules) vers des juridictions sous embargo de luxe, souvent via pays relais.",
  "Des paiements de montres de haute horlogerie partent vers un relais d'Asie centrale, volume ×6 depuis l'embargo.",
  "Volume par corridor relais × catégorie de biens embargo × croissance anormale post-sanctions.",
  "Signal LUXURY_EMBARGO (Niveau 2) — destinataire final et usage à corroborer.",
  [["categories_luxe","catégories surveillées","tenant","-"]],
  [TP("CLI-00080","Négociant horloger multipliant par 6 ses exports vers un relais notoire de réexportation — contournement confirmé."),
   FP("CLI-00063","Croissance liée à l'ouverture documentée d'une boutique franchisée locale (bail et licence fournis) — marché réel, FP.")]),

# ══ BLOC 60 — IMMOBILIER & ART (R396-R398) ══
R("IA-01","R396","Immobilier & Art","Immobilier via structure + prix hors marché","🏘",2,False,
  "Acquisition immobilière via structure (SCI, trust, offshore) à un prix significativement hors marché.",
  "Un bien estimé CHF 2.1M est acquis 3.4M via une société des BVI financée depuis le compte.",
  "Écart au prix de référence (m², registre) × acquisition via structure × origine du financement.",
  "Signal REAL_ESTATE_ANOMALY (Niveau 2) — expertise indépendante et SOW exigées.",
  [["ecart_marche_max","écart au marché toléré","25","%"]],
  [TP("CLI-00005","Surpaiement de 60% via structure BVI : la survaleur revenait au vendeur complice — intégration confirmée."),
   FP("CLI-00152","Prime de 30% pour un bien de prestige off-market avec deux expertises concordantes au dossier — marché de niche, FP.")]),
R("IA-02","R397","Immobilier & Art","Art & ports francs","🖼",2,False,
  "Achat d'œuvres, dépôt en port franc, revente rapide — valeur mobile, opaque et transfrontalière.",
  "Une œuvre achetée CHF 900k est déposée en port franc puis revendue 15 mois après à une partie liée, +40%.",
  "Cycle achat→port franc→revente × délai × lien entre parties × écart de prix.",
  "Signal ART_FREEPORT (Niveau 2) — provenance de l'œuvre et indépendance de l'acheteur à établir.",
  [["delai_revente_min","revente considérée rapide si <","36","mois"]],
  [TP("CLI-00034","Aller-retour d'une œuvre entre deux entités du même bénéficiaire avec +40% — transfert de valeur habillé, TP."),
   FP("CLI-00016","Collectionneur établi cédant une pièce via une maison de vente publique (adjudication tierce, catalogue) — vente de marché, FP.")]),
R("IA-03","R398","Immobilier & Art","Véhicules de valeur (luxe, NFT)","🚗",2,False,
  "Biens de luxe et actifs numériques de collection utilisés comme véhicules de transfert de valeur.",
  "Trois véhicules de collection achetés et réexpédiés à l'étranger en 4 mois, revendus à des parties inconnues.",
  "Fréquence d'achat/revente de biens de valeur × export × contreparties.",
  "Signal VALUE_VEHICLE (Niveau 2) — finalité patrimoniale vs circulation de valeur à clarifier.",
  [["seuil_biens_valeur","équivalent CHF / 180j","200000","CHF"]],
  [TP("CLI-00080","Rotation de véhicules de collection exportés vers un marchand relais, marges incohérentes — circulation de valeur, TP."),
   FP("CLI-00063","Passionné documenté (assurances, expertises, participation à des concours d'élégance) constituant sa collection — FP.")]),

# ══ BLOC 61 — ANALYTIQUE 2G (R399-R403) ══
R("AN-01","R399","Analytique 2G","Déviation au groupe de pairs","📉",2,False,
  "Écart statistique du client à son groupe de pairs CPSI (z-score sur les attributs surveillés), au-delà des seuils fixes de 1re génération.",
  "Un client du groupe « Affluent CH » présente un volume cash à 4.2 écarts-types de la médiane de son groupe.",
  "Z-score robuste (médiane/MAD) par attribut et par groupe, recalculé au fil de l'eau.",
  "Signal PEER_DEVIATION (Niveau 2) — explicable par construction : attribut, valeur, distribution du groupe joints (R44 : l'IA éclaire).",
  [["zscore_seuil","z-score de déclenchement","3.5","σ"]],
  [TP("CLI-00072","Cash à 4.2σ du groupe sans changement déclaré de situation — activité non expliquée, TP."),
   FP("CLI-00104","Pic à 3.8σ expliqué par la vente documentée d'une entreprise (CoC ouvert en amont) — événement de vie, FP.")]),
R("AN-02","R400","Analytique 2G","Rupture de comportement (baseline propre)","⚡",2,False,
  "Changement soudain vs la baseline historique du client lui-même (pas du groupe) : régime transactionnel qui bascule.",
  "Un compte stable depuis 4 ans triple sa volumétrie et change de corridors en 3 semaines.",
  "Détection de rupture (changepoint) sur volume, fréquence, corridors, contreparties vs baseline 12 mois.",
  "Signal BEHAVIOR_SHIFT (Niveau 2) — comparatif avant/après joint au signal.",
  [["sensibilite_rupture","sensibilité du détecteur","tenant","-"]],
  [TP("CLI-00099","Bascule complète du profil (nouveaux corridors, volumes ×3) après un changement de mandataire — compte repris en main par un tiers, TP."),
   FP("CLI-00016","Montée en charge annoncée d'un mandat de gestion élargi (avenant signé) — changement contractualisé, FP.")]),
R("AN-03","R401","Analytique 2G","First-time patterns","🆕",1,False,
  "Premières occurrences sensibles : premier virement international, premier cash, première contrepartie HRJ, premier produit à risque.",
  "Un client 100% domestique depuis 6 ans émet son premier virement vers une juridiction à risque, montant élevé.",
  "Détection de première occurrence par dimension sensible × matérialité du montant.",
  "Signal FIRST_TIME (Niveau 1) — friction douce : revue rapide, pas de blocage (R39 : mesurer, pas coercer).",
  [["dimensions_ft","dimensions surveillées","international,cash,HRJ,produit_risque","-"],["materialite_ft","matérialité minimale","25000","CHF"]],
  [TP("CLI-00069","Premier international du compte : 180k vers une fiduciaire offshore inconnue, dossier à 2% de complétude — TP."),
   FP("CLI-00121","Premier virement France→UK pour l'inscription universitaire d'un enfant (attestation jointe) — vie courante, FP.")]),
R("AN-04","R402","Analytique 2G","Dormance partielle par segment","😴",2,False,
  "Réactivation d'un segment d'activité dormant (ex. le cash après 3 ans d'inactivité cash) même si le compte global reste actif — complète la règle « compte dormant » existante.",
  "Un compte actif en titres n'a fait aucun cash depuis 3 ans ; 3 dépôts espèces surviennent en 2 semaines.",
  "Dormance mesurée par segment (cash, international, produit) ; réactivation = première activité du segment après N mois.",
  "Signal SEGMENT_REACTIVATION (Niveau 2) — contexte de réactivation demandé.",
  [["dormance_segment","dormance du segment","24","mois"]],
  [TP("CLI-00156","Segment cash réactivé par des dépôts fractionnés après 3 ans — le canal oublié sert au placement, TP."),
   FP("CLI-00053","Retraits cash réactivés pour des travaux payés en espèces à des artisans (devis et factures fournis) — usage ponctuel expliqué, FP.")]),
R("AN-05","R403","Analytique 2G","Revenus entrants incohérents (mismatch)","💰",2,False,
  "Entrées récurrentes libellées « salaire/honoraires » incohérentes avec l'employeur et la rémunération déclarés au KYC — pendant entrant de R201/AML-WC-01.",
  "Un « salaire » mensuel de CHF 45k est crédité alors que le KYC déclare 12k et un autre employeur.",
  "Croisement libellé/ordonnateur des entrées récurrentes × rémunération et employeur déclarés.",
  "Signal INCOME_MISMATCH (Niveau 2) — mise à jour KYC ou justification exigée (CoC).",
  [["ecart_revenu_max","écart toléré vs déclaré","50","%"]],
  [TP("CLI-00080","« Salaires » de 45k versés par une société sans lien avec l'employeur déclaré — canal de distribution occulte, TP."),
   FP("CLI-00035","Bonus exceptionnel documenté par le certificat de salaire annuel (élément variable déclaré) — rémunération réelle, FP.")]),
]
