/**
 * i18n — dette produit §10 (RATIFIÉE « tout ratifié », 2026-07-28). La SOURCE est le
 * dictionnaire I18N de la maquette `demo/olive-demo.html` (G2 : « les libellés FR livrés
 * SONT les clés du dictionnaire ») — recopié VERBATIM, zéro traduction inventée.
 * Doctrine « écart par clé » : une clé absente du dictionnaire reste rendue EN FRANÇAIS
 * (le repli est la clé elle-même, exactement le `tr()` de la maquette) — jamais un trou,
 * jamais une invention ; chaque clé manquante se comble par un ajout au dictionnaire.
 * La langue est un choix d'AFFICHAGE (localStorage OLIVE_LANG) — aucune donnée métier
 * n'est traduite : ce qui vient du backend s'affiche tel quel (FE-04).
 */

export type Langue = "FR" | "EN" | "DE" | "IT";
export const LANGUES: Langue[] = ["FR", "EN", "DE", "IT"];

// ── Dictionnaire de la maquette, VERBATIM (FR = clé) ──
const DICT: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA Analyzer", "Multi-devise & FX": "Multi-Currency & FX", "Exécution & Settlement": "Execution & Settlement", "Legal — Contrats": "Legal — Contracts", "Pré-prospection": "Pre-Prospecting", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Central Dashboard", "Clients & Relations": "Clients & Relationships", "Prospect à contacter": "Prospects to contact", "Prospect en contact": "Prospects in contact", "Prospect à onboarder": "Prospects to onboard", "Clients": "Clients", "Personnes": "Persons", "KYC": "KYC", "Account Review": "Account Review", "Change of Circumstances": "Change of Circumstances", "Offboarding": "Offboarding", "Front & Croissance": "Front & Growth", "CRM Banque": "Bank CRM", "Contact Reports": "Contact Reports", "Prochaines actions": "Next Best Actions", "Tâches": "Tasks", "Business Trip": "Business Trip", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risk", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "AML Investigation", "Investigation financière": "Financial Investigation", "Transactions Risk Monitoring": "Transactions Risk Monitoring", "Transferts & ordres": "Transfers & Orders", "Registre LBA": "AMLA Register", "Corroboration KYC": "KYC Corroboration", "Reporting réglementaire": "Regulatory Reporting", "Formations & habilitations": "Training & Certifications", "Veille réglementaire": "Regulatory Watch", "Wealth & Marchés": "Wealth & Markets", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Executive Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Custom Reporting", "GED — Documents": "DMS — Documents", "API & Intégrations": "API & Integrations", "Intégrations": "Integrations", "Configuration": "Configuration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow Management", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Vendor Administration" },
  DE: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA-Analysator", "Multi-devise & FX": "Mehrwährung & FX", "Exécution & Settlement": "Ausführung & Abwicklung", "Legal — Contrats": "Legal — Verträge", "Pré-prospection": "Vor-Akquise", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Startseite", "Dashboard central": "Zentrales Dashboard", "Clients & Relations": "Kunden & Beziehungen", "Prospect à contacter": "Zu kontaktierende Prospects", "Prospect en contact": "Prospects in Kontakt", "Prospect à onboarder": "Zu eröffnende Prospects", "Clients": "Kunden", "Personnes": "Personen", "KYC": "KYC", "Account Review": "Periodische Überprüfung", "Change of Circumstances": "Änderung der Verhältnisse", "Offboarding": "Saldierung", "Front & Croissance": "Front & Wachstum", "CRM Banque": "Bank-CRM", "Contact Reports": "Kontaktberichte", "Prochaines actions": "Nächste Aktionen", "Tâches": "Aufgaben", "Business Trip": "Geschäftsreisen", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risiko", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "GwG-Ermittlung", "Investigation financière": "Finanzermittlung", "Transactions Risk Monitoring": "Transaktionsüberwachung", "Transferts & ordres": "Überweisungen & Aufträge", "Registre LBA": "GwG-Register", "Corroboration KYC": "KYC-Plausibilisierung", "Reporting réglementaire": "Regulatorisches Reporting", "Formations & habilitations": "Schulungen & Berechtigungen", "Veille réglementaire": "Regulatorische Beobachtung", "Wealth & Marchés": "Wealth & Märkte", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Führungs-Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Individuelles Reporting", "GED — Documents": "DMS — Dokumente", "API & Intégrations": "API & Integrationen", "Intégrations": "Integrationen", "Configuration": "Konfiguration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow-Verwaltung", "Questionnaire Builder": "Fragebogen-Builder", "Administration Éditeur": "Hersteller-Administration" },
  IT: { "Analyseur SWIFT/SEPA": "Analizzatore SWIFT/SEPA", "Multi-devise & FX": "Multi-valuta & FX", "Exécution & Settlement": "Esecuzione & Regolamento", "Legal — Contrats": "Legal — Contratti", "Pré-prospection": "Pre-prospezione", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Dashboard centrale", "Clients & Relations": "Clienti & Relazioni", "Prospect à contacter": "Prospect da contattare", "Prospect en contact": "Prospect in contatto", "Prospect à onboarder": "Prospect da aprire", "Clients": "Clienti", "Personnes": "Persone", "KYC": "KYC", "Account Review": "Revisione periodica", "Change of Circumstances": "Cambiamento di circostanze", "Offboarding": "Chiusura relazione", "Front & Croissance": "Front & Crescita", "CRM Banque": "CRM Banca", "Contact Reports": "Rapporti di contatto", "Prochaines actions": "Prossime azioni", "Tâches": "Attività", "Business Trip": "Viaggi d'affari", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Rischio", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "Indagine LRD", "Investigation financière": "Indagine finanziaria", "Transactions Risk Monitoring": "Monitoraggio transazioni", "Transferts & ordres": "Bonifici & ordini", "Registre LBA": "Registro LRD", "Corroboration KYC": "Corroborazione KYC", "Reporting réglementaire": "Reporting regolamentare", "Formations & habilitations": "Formazione & abilitazioni", "Veille réglementaire": "Osservatorio normativo", "Wealth & Marchés": "Wealth & Mercati", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Dashboard esecutivo", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Reporting su misura", "GED — Documents": "GED — Documenti", "API & Intégrations": "API & Integrazioni", "Intégrations": "Integrazioni", "Configuration": "Configurazione", "Administration": "Amministrazione", "Workflow Builder": "Workflow Builder", "Workflow Management": "Gestione workflow", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Amministrazione fornitore" },
};

// ── Extension ÉDITEUR (tour 2 du cliquet, 2026-07-29) : clés POST-maquette — « chaque clé
// manquante se comble par un AJOUT au dictionnaire » (R326). Les libellés d'interface sont
// du texte de l'ÉDITEUR (précédent : gabarits OF-09) — jamais une donnée métier. La clé
// « Octopulse OpRisk » corrige le sic maquette (« OppRisk ») : la maquette cède au canon.
const EXT: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Profilage CPSI": "CPSI Profiling", "Transactions & Marchés": "Transactions & Markets", "Audit": "Audit", "Recette client (BAT)": "Client Acceptance (BAT)", "Bac à sable KYC": "KYC Sandbox", "Bac à sable BRM": "BRM Sandbox", "Bac à sable Central File": "Central File Sandbox", "Bac à sable Workflow": "Workflow Sandbox", "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Advanced Screening", "File d'alertes": "Alert Queue", "Dossiers de risque": "Risk Cases", "Personnes / UBO": "Persons / UBO", "Chgt circonstances": "Change of Circumstances", "Custody & TA": "Custody & TA", "Settlement": "Settlement", "Reporting MROS": "MROS Reporting", "Pièces (GED)": "Documents (DMS)", "GED / coffre": "DMS / Vault", "Workflow": "Workflow", "Paramétrage": "Settings", "Config & Go-live": "Config & Go-live", "Référentiel AML": "AML Reference", "Bac à sable AML": "AML Sandbox", "Bac à sable Onboarding": "Onboarding Sandbox", "Ports": "Ports", "Workflow Instances": "Workflow Instances", "Formations": "Training", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "KYC Replay As-Of", "Règles AML": "AML Rules", "AML Gap": "AML Gap", "Finance Islamique": "Islamic Finance", "CPSI · Profil": "CPSI · Profile", "CPSI · Segmentation": "CPSI · Segmentation", "CPSI · Risk cases": "CPSI · Risk Cases", "CPSI · Barèmes": "CPSI · Scales", "CPSI · Guide": "CPSI · Guide", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sections & Rights", "Profils AR": "AR Profiles", "Profils GAR": "GAR Profiles", "Registre paramètres": "Parameter Registry", "Matrice documentaire": "Document Matrix", "Types de CoC": "CoC Types", "Bacs à sable": "Sandboxes", "Audit & transport": "Audit & Transport", "Audit IT": "IT Audit", "Utilisateurs & rôles": "Users & Roles", "Guide IAM": "IAM Guide", "SSO / Fédération": "SSO / Federation" },
  DE: { "Profilage CPSI": "CPSI-Profiling", "Transactions & Marchés": "Transaktionen & Märkte", "Audit": "Audit", "Recette client (BAT)": "Kundenabnahme (BAT)", "Bac à sable KYC": "KYC-Sandbox", "Bac à sable BRM": "BRM-Sandbox", "Bac à sable Central File": "Central-File-Sandbox", "Bac à sable Workflow": "Workflow-Sandbox", "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Erweitertes Screening", "File d'alertes": "Alert-Warteschlange", "Dossiers de risque": "Risikodossiers", "Personnes / UBO": "Personen / UBO", "Chgt circonstances": "Änderung der Verhältnisse", "Custody & TA": "Custody & TA", "Settlement": "Abwicklung", "Reporting MROS": "MROS-Meldungen", "Pièces (GED)": "Dokumente (DMS)", "GED / coffre": "DMS / Tresor", "Workflow": "Workflow", "Paramétrage": "Parametrierung", "Config & Go-live": "Konfiguration & Go-live", "Référentiel AML": "GwG-Referenzdaten", "Bac à sable AML": "GwG-Sandbox", "Bac à sable Onboarding": "Onboarding-Sandbox", "Ports": "Ports", "Workflow Instances": "Workflow-Instanzen", "Formations": "Schulungen", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "KYC-Replay zum Stichtag", "Règles AML": "GwG-Regeln", "AML Gap": "AML Gap", "Finance Islamique": "Islamic Finance", "CPSI · Profil": "CPSI · Profil", "CPSI · Segmentation": "CPSI · Segmentierung", "CPSI · Risk cases": "CPSI · Risk Cases", "CPSI · Barèmes": "CPSI · Skalen", "CPSI · Guide": "CPSI · Leitfaden", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sektionen & Rechte", "Profils AR": "AR-Profile", "Profils GAR": "GAR-Profile", "Registre paramètres": "Parameterregister", "Matrice documentaire": "Dokumentenmatrix", "Types de CoC": "CoC-Typen", "Bacs à sable": "Sandboxes", "Audit & transport": "Audit & Transport", "Audit IT": "IT-Audit", "Utilisateurs & rôles": "Benutzer & Rollen", "Guide IAM": "IAM-Leitfaden", "SSO / Fédération": "SSO / Föderation" },
  IT: { "Profilage CPSI": "Profilazione CPSI", "Transactions & Marchés": "Transazioni & Mercati", "Audit": "Audit", "Recette client (BAT)": "Collaudo cliente (BAT)", "Bac à sable KYC": "Sandbox KYC", "Bac à sable BRM": "Sandbox BRM", "Bac à sable Central File": "Sandbox Central File", "Bac à sable Workflow": "Sandbox Workflow", "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Screening avanzato", "File d'alertes": "Coda degli alert", "Dossiers de risque": "Dossier di rischio", "Personnes / UBO": "Persone / UBO", "Chgt circonstances": "Cambiamento di circostanze", "Custody & TA": "Custody & TA", "Settlement": "Regolamento", "Reporting MROS": "Reporting MROS", "Pièces (GED)": "Documenti (GED)", "GED / coffre": "GED / cassaforte", "Workflow": "Workflow", "Paramétrage": "Parametrizzazione", "Config & Go-live": "Config & Go-live", "Référentiel AML": "Referenziale LRD", "Bac à sable AML": "Sandbox LRD", "Bac à sable Onboarding": "Sandbox Onboarding", "Ports": "Ports", "Workflow Instances": "Istanze workflow", "Formations": "Formazione", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "Replay KYC a data", "Règles AML": "Regole LRD", "AML Gap": "AML Gap", "Finance Islamique": "Finanza islamica", "CPSI · Profil": "CPSI · Profilo", "CPSI · Segmentation": "CPSI · Segmentazione", "CPSI · Risk cases": "CPSI · Risk cases", "CPSI · Barèmes": "CPSI · Scale", "CPSI · Guide": "CPSI · Guida", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sezioni & diritti", "Profils AR": "Profili AR", "Profils GAR": "Profili GAR", "Registre paramètres": "Registro parametri", "Matrice documentaire": "Matrice documentale", "Types de CoC": "Tipi di CoC", "Bacs à sable": "Sandbox", "Audit & transport": "Audit & trasporto", "Audit IT": "Audit IT", "Utilisateurs & rôles": "Utenti & ruoli", "Guide IAM": "Guida IAM", "SSO / Fédération": "SSO / Federazione" },
};
for (const l of ["EN", "DE", "IT"] as const) Object.assign(DICT[l], EXT[l]);

// ── Contenus d'écrans (tour 3 du cliquet — un bloc par écran converti, clés FR) ──
const ECRANS: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Session expirée — reconnectez-vous (votre brouillon en cours est conservé).": "Session expired — sign in again (your current draft is preserved).", "e-mail": "e-mail", "mot de passe": "password", "Se reconnecter": "Sign in again", "Connexion impossible — vérifiez le réseau.": "Unable to connect — check the network.", "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Custom Reporting (declared projections only — zero free-form SQL)", "Charger l'annuaire": "Load the directory", "Interroger": "Query", "ligne(s) source (scopées BACKEND) · sensibilité": "source row(s) (scoped BACKEND) · sensitivity", "Chargement de l'écran…": "Loading screen…",
    "Octopulse OpRisk — incidents opérationnels (dossiers tracés, taxonomie Bâle du tenant)": "Octopulse OpRisk — operational incidents (tracked cases, tenant Basel taxonomy)", "Charger": "Load", "titre de l'incident": "incident title", "catégorie Bâle": "Basel category", "Déclarer": "Report", "Heatmap (CALCULÉE serveur — fréquence × sévérité, rejouable à date ; aucune cellule ne se saisit)": "Heatmap (server-COMPUTED — frequency × severity, replayable as-of; no cell is ever entered)", "catégorie": "category", "fréquence": "frequency", "sévérité max": "max severity", "score": "score", "Incidents": "Incidents", "sévérité": "severity", "Analyser": "Analyse", "Clore (motivé)": "Close (with reason)", "Plan d'action (le retard est un fait calculé — notifié, jamais bloquant)": "Action plan (lateness is a computed fact — notified, never blocking)", "EN RETARD": "OVERDUE",
    "document": "document", "compte": "account",
    "Mobile Banking — face banque (population cliente DISTINCTE, jamais un rôle interne)": "Mobile Banking — bank side (DISTINCT client population, never an internal role)", "v1 = lecture + messagerie côté client. Le client ne voit QUE le partagé (rien par défaut) ; aucune donnée compliance ne sort — contrôle SERVEUR, l'app est un rendu.": "v1 = read + messaging on the client side. The client sees ONLY what is shared (nothing by default); no compliance data ever leaves — SERVER-side control, the app is a rendering.", "Activer le canal (RM)": "Activate the channel (RM)", "Messagerie": "Messaging", "Identité": "Identity", "code hors bande": "out-of-band code", "remis UNE fois, à transmettre HORS canal (l'événement ne le porte jamais).": "issued ONCE, to be transmitted OUT of channel (the event never carries it).", "documentId (GED)": "documentId (DMS)", "référence du compte": "account reference", "Marqué « partagé client » — acte tracé.": "Marked “client-shared” — tracked act.", "Marquer partagé": "Mark as shared", "rien n'est partagé par défaut (R318)": "nothing is shared by default (R318)", "Fil du client": "Client thread", "Aucun message.": "No messages.", "CoC ouvert": "CoC opened", "la demande suit la voie R276, jamais un second circuit.": "the request follows the R276 path, never a second circuit.", "Ouvrir un CoC": "Open a CoC", "répondre au client": "reply to the client", "Réponse envoyée.": "Reply sent.", "Envoyer": "Send" },
  DE: { "Session expirée — reconnectez-vous (votre brouillon en cours est conservé).": "Sitzung abgelaufen — melden Sie sich erneut an (Ihr Entwurf bleibt erhalten).", "e-mail": "E-Mail", "mot de passe": "Passwort", "Se reconnecter": "Erneut anmelden", "Connexion impossible — vérifiez le réseau.": "Verbindung nicht möglich — Netzwerk prüfen.", "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Individuelles Reporting (nur deklarierte Projektionen — kein freies SQL)", "Charger l'annuaire": "Verzeichnis laden", "Interroger": "Abfragen", "ligne(s) source (scopées BACKEND) · sensibilité": "Quellzeile(n) (BACKEND-gescoped) · Sensibilität", "Chargement de l'écran…": "Bildschirm wird geladen…",
    "Octopulse OpRisk — incidents opérationnels (dossiers tracés, taxonomie Bâle du tenant)": "Octopulse OpRisk — operationelle Vorfälle (nachvollziehbare Dossiers, Basel-Taxonomie des Mandanten)", "Charger": "Laden", "titre de l'incident": "Titel des Vorfalls", "catégorie Bâle": "Basel-Kategorie", "Déclarer": "Melden", "Heatmap (CALCULÉE serveur — fréquence × sévérité, rejouable à date ; aucune cellule ne se saisit)": "Heatmap (server-BERECHNET — Häufigkeit × Schweregrad, stichtagsfähig; keine Zelle wird je erfasst)", "catégorie": "Kategorie", "fréquence": "Häufigkeit", "sévérité max": "max. Schweregrad", "score": "Score", "Incidents": "Vorfälle", "sévérité": "Schweregrad", "Analyser": "Analysieren", "Clore (motivé)": "Schliessen (begründet)", "Plan d'action (le retard est un fait calculé — notifié, jamais bloquant)": "Massnahmenplan (Verzug ist ein berechneter Fakt — notifiziert, nie blockierend)", "EN RETARD": "IN VERZUG",
    "document": "Dokument", "compte": "Konto",
    "Mobile Banking — face banque (population cliente DISTINCTE, jamais un rôle interne)": "Mobile Banking — Bankseite (GETRENNTE Kundenpopulation, nie eine interne Rolle)", "v1 = lecture + messagerie côté client. Le client ne voit QUE le partagé (rien par défaut) ; aucune donnée compliance ne sort — contrôle SERVEUR, l'app est un rendu.": "v1 = Lesen + Nachrichten auf Kundenseite. Der Kunde sieht NUR das Geteilte (nichts als Standard); keine Compliance-Daten verlassen das Haus — SERVER-seitige Kontrolle, die App ist eine Darstellung.", "Activer le canal (RM)": "Kanal aktivieren (RM)", "Messagerie": "Nachrichten", "Identité": "Identität", "code hors bande": "Out-of-Band-Code", "remis UNE fois, à transmettre HORS canal (l'événement ne le porte jamais).": "EINMAL ausgegeben, AUSSERHALB des Kanals zu übermitteln (das Ereignis trägt ihn nie).", "documentId (GED)": "documentId (DMS)", "référence du compte": "Kontoreferenz", "Marqué « partagé client » — acte tracé.": "Als «kundengeteilt» markiert — nachvollziehbarer Akt.", "Marquer partagé": "Als geteilt markieren", "rien n'est partagé par défaut (R318)": "nichts ist standardmässig geteilt (R318)", "Fil du client": "Kundenverlauf", "Aucun message.": "Keine Nachrichten.", "CoC ouvert": "CoC eröffnet", "la demande suit la voie R276, jamais un second circuit.": "die Anfrage folgt dem R276-Weg, nie einem zweiten Kreislauf.", "Ouvrir un CoC": "CoC eröffnen", "répondre au client": "dem Kunden antworten", "Réponse envoyée.": "Antwort gesendet.", "Envoyer": "Senden" },
  IT: { "Session expirée — reconnectez-vous (votre brouillon en cours est conservé).": "Sessione scaduta — riconnettetevi (la bozza in corso è conservata).", "e-mail": "e-mail", "mot de passe": "password", "Se reconnecter": "Riconnettersi", "Connexion impossible — vérifiez le réseau.": "Connessione impossibile — verificare la rete.", "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Reporting su misura (solo proiezioni dichiarate — zero SQL libero)", "Charger l'annuaire": "Caricare l'elenco", "Interroger": "Interrogare", "ligne(s) source (scopées BACKEND) · sensibilité": "riga/e sorgente (scope BACKEND) · sensibilità", "Chargement de l'écran…": "Caricamento della schermata…",
    "Octopulse OpRisk — incidents opérationnels (dossiers tracés, taxonomie Bâle du tenant)": "Octopulse OpRisk — incidenti operativi (dossier tracciati, tassonomia Basilea del tenant)", "Charger": "Caricare", "titre de l'incident": "titolo dell'incidente", "catégorie Bâle": "categoria Basilea", "Déclarer": "Dichiarare", "Heatmap (CALCULÉE serveur — fréquence × sévérité, rejouable à date ; aucune cellule ne se saisit)": "Heatmap (CALCOLATA dal server — frequenza × severità, riproducibile a data; nessuna cella viene mai inserita)", "catégorie": "categoria", "fréquence": "frequenza", "sévérité max": "severità max", "score": "punteggio", "Incidents": "Incidenti", "sévérité": "severità", "Analyser": "Analizzare", "Clore (motivé)": "Chiudere (motivato)", "Plan d'action (le retard est un fait calculé — notifié, jamais bloquant)": "Piano d'azione (il ritardo è un fatto calcolato — notificato, mai bloccante)", "EN RETARD": "IN RITARDO",
    "document": "documento", "compte": "conto",
    "Mobile Banking — face banque (population cliente DISTINCTE, jamais un rôle interne)": "Mobile Banking — lato banca (popolazione clienti DISTINTA, mai un ruolo interno)", "v1 = lecture + messagerie côté client. Le client ne voit QUE le partagé (rien par défaut) ; aucune donnée compliance ne sort — contrôle SERVEUR, l'app est un rendu.": "v1 = lettura + messaggistica lato cliente. Il cliente vede SOLO ciò che è condiviso (nulla per default); nessun dato compliance esce — controllo lato SERVER, l'app è una resa.", "Activer le canal (RM)": "Attivare il canale (RM)", "Messagerie": "Messaggistica", "Identité": "Identità", "code hors bande": "codice fuori banda", "remis UNE fois, à transmettre HORS canal (l'événement ne le porte jamais).": "consegnato UNA volta, da trasmettere FUORI canale (l'evento non lo porta mai).", "documentId (GED)": "documentId (GED)", "référence du compte": "riferimento del conto", "Marqué « partagé client » — acte tracé.": "Contrassegnato «condiviso cliente» — atto tracciato.", "Marquer partagé": "Contrassegnare condiviso", "rien n'est partagé par défaut (R318)": "nulla è condiviso per default (R318)", "Fil du client": "Filo del cliente", "Aucun message.": "Nessun messaggio.", "CoC ouvert": "CoC aperto", "la demande suit la voie R276, jamais un second circuit.": "la richiesta segue la via R276, mai un secondo circuito.", "Ouvrir un CoC": "Aprire un CoC", "répondre au client": "rispondere al cliente", "Réponse envoyée.": "Risposta inviata.", "Envoyer": "Inviare" },
};
for (const l of ["EN", "DE", "IT"] as const) Object.assign(DICT[l], ECRANS[l]);

export function langue(): Langue {
  try {
    const l = window.localStorage.getItem("OLIVE_LANG") as Langue | null;
    return l && LANGUES.includes(l) ? l : "FR";
  } catch { return "FR"; }
}

export function setLangue(l: Langue) {
  try { window.localStorage.setItem("OLIVE_LANG", l); } catch { /* stockage indisponible — la langue reste FR */ }
}

/**
 * Le `tr()` de la maquette : traduction si la clé existe, sinon la clé FR (écart par clé).
 * R326/LN-02 (ratifié 2026-07-29) : la clé MANQUANTE se voit — marqueur ⟦…⟧ en DEV
 * uniquement (repli FR PROPRE en prod, jamais une clé brute maquillée) ; FR = langue de
 * référence, jamais marquée (la clé EST le FR).
 */
export function traduire(l: Langue, opts?: { dev?: boolean }): (cle: string) => string {
  if (l === "FR") return (cle) => cle;
  const dev = opts?.dev ?? (typeof import.meta !== "undefined" && Boolean((import.meta as { env?: { DEV?: boolean } }).env?.DEV));
  const d = DICT[l];
  return (cle) => d[cle] ?? (dev ? `⟦${cle}⟧` : cle);
}

/**
 * R327/LN-06 : le NOMBRE suit la LOCALE de l'utilisateur, la DEVISE suit la DONNÉE —
 * jamais l'inverse. Intl fait foi par locale (les littéraux d'exemple du canon sont
 * illustratifs — consigné).
 */
export function formatMontant(montant: number, devise: string, locale: string): string {
  return new Intl.NumberFormat(locale, { style: "currency", currency: devise }).format(montant);
}
