/**
 * i18n — dette produit §10 (RATIFIÉE « tout ratifié », 2026-07-28). La SOURCE est le
 * dictionnaire I18N de la maquette `demo/olive-demo.html` (G2 : « les libellés FR livrés
 * SONT les clés du dictionnaire ») — recopié VERBATIM, zéro traduction inventée.
 * Doctrine « écart par clé » : une clé absente du dictionnaire reste rendue EN FRANÇAIS
 * (le repli est la clé elle-même, exactement le `tr()` de la maquette) — jamais un trou,
 * jamais une invention ; chaque clé manquante se comble par un ajout au dictionnaire.
 * La langue est un choix d'AFFICHAGE (localStorage OLIVE_LANG) — aucune donnée métier
 * n'est traduite : ce qui vient du backend s'affiche tel quel (FE-04).
 */

export type Langue = "FR" | "EN" | "DE" | "IT";
export const LANGUES: Langue[] = ["FR", "EN", "DE", "IT"];

// ── Dictionnaire de la maquette, VERBATIM (FR = clé) ──
const DICT: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA Analyzer", "Multi-devise & FX": "Multi-Currency & FX", "Exécution & Settlement": "Execution & Settlement", "Legal — Contrats": "Legal — Contracts", "Pré-prospection": "Pre-Prospecting", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Central Dashboard", "Clients & Relations": "Clients & Relationships", "Prospect à contacter": "Prospects to contact", "Prospect en contact": "Prospects in contact", "Prospect à onboarder": "Prospects to onboard", "Clients": "Clients", "Personnes": "Persons", "KYC": "KYC", "Account Review": "Account Review", "Change of Circumstances": "Change of Circumstances", "Offboarding": "Offboarding", "Front & Croissance": "Front & Growth", "CRM Banque": "Bank CRM", "Contact Reports": "Contact Reports", "Prochaines actions": "Next Best Actions", "Tâches": "Tasks", "Business Trip": "Business Trip", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risk", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "AML Investigation", "Investigation financière": "Financial Investigation", "Transactions Risk Monitoring": "Transactions Risk Monitoring", "Transferts & ordres": "Transfers & Orders", "Registre LBA": "AMLA Register", "Corroboration KYC": "KYC Corroboration", "Reporting réglementaire": "Regulatory Reporting", "Formations & habilitations": "Training & Certifications", "Veille réglementaire": "Regulatory Watch", "Wealth & Marchés": "Wealth & Markets", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Executive Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Custom Reporting", "GED — Documents": "DMS — Documents", "API & Intégrations": "API & Integrations", "Intégrations": "Integrations", "Configuration": "Configuration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow Management", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Vendor Administration" },
  DE: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA-Analysator", "Multi-devise & FX": "Mehrwährung & FX", "Exécution & Settlement": "Ausführung & Abwicklung", "Legal — Contrats": "Legal — Verträge", "Pré-prospection": "Vor-Akquise", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Startseite", "Dashboard central": "Zentrales Dashboard", "Clients & Relations": "Kunden & Beziehungen", "Prospect à contacter": "Zu kontaktierende Prospects", "Prospect en contact": "Prospects in Kontakt", "Prospect à onboarder": "Zu eröffnende Prospects", "Clients": "Kunden", "Personnes": "Personen", "KYC": "KYC", "Account Review": "Periodische Überprüfung", "Change of Circumstances": "Änderung der Verhältnisse", "Offboarding": "Saldierung", "Front & Croissance": "Front & Wachstum", "CRM Banque": "Bank-CRM", "Contact Reports": "Kontaktberichte", "Prochaines actions": "Nächste Aktionen", "Tâches": "Aufgaben", "Business Trip": "Geschäftsreisen", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risiko", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "GwG-Ermittlung", "Investigation financière": "Finanzermittlung", "Transactions Risk Monitoring": "Transaktionsüberwachung", "Transferts & ordres": "Überweisungen & Aufträge", "Registre LBA": "GwG-Register", "Corroboration KYC": "KYC-Plausibilisierung", "Reporting réglementaire": "Regulatorisches Reporting", "Formations & habilitations": "Schulungen & Berechtigungen", "Veille réglementaire": "Regulatorische Beobachtung", "Wealth & Marchés": "Wealth & Märkte", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Führungs-Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Individuelles Reporting", "GED — Documents": "DMS — Dokumente", "API & Intégrations": "API & Integrationen", "Intégrations": "Integrationen", "Configuration": "Konfiguration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow-Verwaltung", "Questionnaire Builder": "Fragebogen-Builder", "Administration Éditeur": "Hersteller-Administration" },
  IT: { "Analyseur SWIFT/SEPA": "Analizzatore SWIFT/SEPA", "Multi-devise & FX": "Multi-valuta & FX", "Exécution & Settlement": "Esecuzione & Regolamento", "Legal — Contrats": "Legal — Contratti", "Pré-prospection": "Pre-prospezione", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Dashboard centrale", "Clients & Relations": "Clienti & Relazioni", "Prospect à contacter": "Prospect da contattare", "Prospect en contact": "Prospect in contatto", "Prospect à onboarder": "Prospect da aprire", "Clients": "Clienti", "Personnes": "Persone", "KYC": "KYC", "Account Review": "Revisione periodica", "Change of Circumstances": "Cambiamento di circostanze", "Offboarding": "Chiusura relazione", "Front & Croissance": "Front & Crescita", "CRM Banque": "CRM Banca", "Contact Reports": "Rapporti di contatto", "Prochaines actions": "Prossime azioni", "Tâches": "Attività", "Business Trip": "Viaggi d'affari", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Rischio", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "Indagine LRD", "Investigation financière": "Indagine finanziaria", "Transactions Risk Monitoring": "Monitoraggio transazioni", "Transferts & ordres": "Bonifici & ordini", "Registre LBA": "Registro LRD", "Corroboration KYC": "Corroborazione KYC", "Reporting réglementaire": "Reporting regolamentare", "Formations & habilitations": "Formazione & abilitazioni", "Veille réglementaire": "Osservatorio normativo", "Wealth & Marchés": "Wealth & Mercati", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Dashboard esecutivo", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Reporting su misura", "GED — Documents": "GED — Documenti", "API & Intégrations": "API & Integrazioni", "Intégrations": "Integrazioni", "Configuration": "Configurazione", "Administration": "Amministrazione", "Workflow Builder": "Workflow Builder", "Workflow Management": "Gestione workflow", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Amministrazione fornitore" },
};

export function langue(): Langue {
  try {
    const l = window.localStorage.getItem("OLIVE_LANG") as Langue | null;
    return l && LANGUES.includes(l) ? l : "FR";
  } catch { return "FR"; }
}

export function setLangue(l: Langue) {
  try { window.localStorage.setItem("OLIVE_LANG", l); } catch { /* stockage indisponible — la langue reste FR */ }
}

/** Le `tr()` de la maquette : traduction si la clé existe, sinon la clé FR (écart par clé). */
export function traduire(l: Langue): (cle: string) => string {
  if (l === "FR") return (cle) => cle;
  const d = DICT[l];
  return (cle) => d[cle] ?? cle;
}
