/**
 * i18n — dette produit §10 (RATIFIÉE « tout ratifié », 2026-07-28). La SOURCE est le
 * dictionnaire I18N de la maquette `demo/olive-demo.html` (G2 : « les libellés FR livrés
 * SONT les clés du dictionnaire ») — recopié VERBATIM, zéro traduction inventée.
 * Doctrine « écart par clé » : une clé absente du dictionnaire reste rendue EN FRANÇAIS
 * (le repli est la clé elle-même, exactement le `tr()` de la maquette) — jamais un trou,
 * jamais une invention ; chaque clé manquante se comble par un ajout au dictionnaire.
 * La langue est un choix d'AFFICHAGE (localStorage OLIVE_LANG) — aucune donnée métier
 * n'est traduite : ce qui vient du backend s'affiche tel quel (FE-04).
 */

export type Langue = "FR" | "EN" | "DE" | "IT";
export const LANGUES: Langue[] = ["FR", "EN", "DE", "IT"];

// ── Dictionnaire de la maquette, VERBATIM (FR = clé) ──
const DICT: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA Analyzer", "Multi-devise & FX": "Multi-Currency & FX", "Exécution & Settlement": "Execution & Settlement", "Legal — Contrats": "Legal — Contracts", "Pré-prospection": "Pre-Prospecting", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Central Dashboard", "Clients & Relations": "Clients & Relationships", "Prospect à contacter": "Prospects to contact", "Prospect en contact": "Prospects in contact", "Prospect à onboarder": "Prospects to onboard", "Clients": "Clients", "Personnes": "Persons", "KYC": "KYC", "Account Review": "Account Review", "Change of Circumstances": "Change of Circumstances", "Offboarding": "Offboarding", "Front & Croissance": "Front & Growth", "CRM Banque": "Bank CRM", "Contact Reports": "Contact Reports", "Prochaines actions": "Next Best Actions", "Tâches": "Tasks", "Business Trip": "Business Trip", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risk", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "AML Investigation", "Investigation financière": "Financial Investigation", "Transactions Risk Monitoring": "Transactions Risk Monitoring", "Transferts & ordres": "Transfers & Orders", "Registre LBA": "AMLA Register", "Corroboration KYC": "KYC Corroboration", "Reporting réglementaire": "Regulatory Reporting", "Formations & habilitations": "Training & Certifications", "Veille réglementaire": "Regulatory Watch", "Wealth & Marchés": "Wealth & Markets", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Executive Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Custom Reporting", "GED — Documents": "DMS — Documents", "API & Intégrations": "API & Integrations", "Intégrations": "Integrations", "Configuration": "Configuration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow Management", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Vendor Administration" },
  DE: { "Analyseur SWIFT/SEPA": "SWIFT/SEPA-Analysator", "Multi-devise & FX": "Mehrwährung & FX", "Exécution & Settlement": "Ausführung & Abwicklung", "Legal — Contrats": "Legal — Verträge", "Pré-prospection": "Vor-Akquise", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Startseite", "Dashboard central": "Zentrales Dashboard", "Clients & Relations": "Kunden & Beziehungen", "Prospect à contacter": "Zu kontaktierende Prospects", "Prospect en contact": "Prospects in Kontakt", "Prospect à onboarder": "Zu eröffnende Prospects", "Clients": "Kunden", "Personnes": "Personen", "KYC": "KYC", "Account Review": "Periodische Überprüfung", "Change of Circumstances": "Änderung der Verhältnisse", "Offboarding": "Saldierung", "Front & Croissance": "Front & Wachstum", "CRM Banque": "Bank-CRM", "Contact Reports": "Kontaktberichte", "Prochaines actions": "Nächste Aktionen", "Tâches": "Aufgaben", "Business Trip": "Geschäftsreisen", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Risiko", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "GwG-Ermittlung", "Investigation financière": "Finanzermittlung", "Transactions Risk Monitoring": "Transaktionsüberwachung", "Transferts & ordres": "Überweisungen & Aufträge", "Registre LBA": "GwG-Register", "Corroboration KYC": "KYC-Plausibilisierung", "Reporting réglementaire": "Regulatorisches Reporting", "Formations & habilitations": "Schulungen & Berechtigungen", "Veille réglementaire": "Regulatorische Beobachtung", "Wealth & Marchés": "Wealth & Märkte", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Führungs-Dashboard", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Individuelles Reporting", "GED — Documents": "DMS — Dokumente", "API & Intégrations": "API & Integrationen", "Intégrations": "Integrationen", "Configuration": "Konfiguration", "Administration": "Administration", "Workflow Builder": "Workflow Builder", "Workflow Management": "Workflow-Verwaltung", "Questionnaire Builder": "Fragebogen-Builder", "Administration Éditeur": "Hersteller-Administration" },
  IT: { "Analyseur SWIFT/SEPA": "Analizzatore SWIFT/SEPA", "Multi-devise & FX": "Multi-valuta & FX", "Exécution & Settlement": "Esecuzione & Regolamento", "Legal — Contrats": "Legal — Contratti", "Pré-prospection": "Pre-prospezione", "Octopulse OppRisk": "Octopulse OpRisk", "Accueil": "Home", "Dashboard central": "Dashboard centrale", "Clients & Relations": "Clienti & Relazioni", "Prospect à contacter": "Prospect da contattare", "Prospect en contact": "Prospect in contatto", "Prospect à onboarder": "Prospect da aprire", "Clients": "Clienti", "Personnes": "Persone", "KYC": "KYC", "Account Review": "Revisione periodica", "Change of Circumstances": "Cambiamento di circostanze", "Offboarding": "Chiusura relazione", "Front & Croissance": "Front & Crescita", "CRM Banque": "CRM Banca", "Contact Reports": "Rapporti di contatto", "Prochaines actions": "Prossime azioni", "Tâches": "Attività", "Business Trip": "Viaggi d'affari", "Cross-Border": "Cross-Border", "Compliance & Risque": "Compliance & Rischio", "Screening": "Screening", "Compliance Center": "Compliance Center", "AML Investigation": "Indagine LRD", "Investigation financière": "Indagine finanziaria", "Transactions Risk Monitoring": "Monitoraggio transazioni", "Transferts & ordres": "Bonifici & ordini", "Registre LBA": "Registro LRD", "Corroboration KYC": "Corroborazione KYC", "Reporting réglementaire": "Reporting regolamentare", "Formations & habilitations": "Formazione & abilitazioni", "Veille réglementaire": "Osservatorio normativo", "Wealth & Marchés": "Wealth & Mercati", "PMS": "PMS", "Mobile Banking": "Mobile Banking", "Dashboard Exécutif": "Dashboard esecutivo", "Data & Intelligence": "Data & Intelligence", "Olivia (AI Core)": "Olivia (AI Core)", "BI — Reporting sur mesure": "BI — Reporting su misura", "GED — Documents": "GED — Documenti", "API & Intégrations": "API & Integrazioni", "Intégrations": "Integrazioni", "Configuration": "Configurazione", "Administration": "Amministrazione", "Workflow Builder": "Workflow Builder", "Workflow Management": "Gestione workflow", "Questionnaire Builder": "Questionnaire Builder", "Administration Éditeur": "Amministrazione fornitore" },
};

// ── Extension ÉDITEUR (tour 2 du cliquet, 2026-07-29) : clés POST-maquette — « chaque clé
// manquante se comble par un AJOUT au dictionnaire » (R326). Les libellés d'interface sont
// du texte de l'ÉDITEUR (précédent : gabarits OF-09) — jamais une donnée métier. La clé
// « Octopulse OpRisk » corrige le sic maquette (« OppRisk ») : la maquette cède au canon.
const EXT: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Advanced Screening", "File d'alertes": "Alert Queue", "Dossiers de risque": "Risk Cases", "Personnes / UBO": "Persons / UBO", "Chgt circonstances": "Change of Circumstances", "Custody & TA": "Custody & TA", "Settlement": "Settlement", "Reporting MROS": "MROS Reporting", "Pièces (GED)": "Documents (DMS)", "GED / coffre": "DMS / Vault", "Workflow": "Workflow", "Paramétrage": "Settings", "Config & Go-live": "Config & Go-live", "Référentiel AML": "AML Reference", "Bac à sable AML": "AML Sandbox", "Bac à sable Onboarding": "Onboarding Sandbox", "Ports": "Ports", "Workflow Instances": "Workflow Instances", "Formations": "Training", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "KYC Replay As-Of", "Règles AML": "AML Rules", "Finance Islamique": "Islamic Finance", "CPSI · Profil": "CPSI · Profile", "CPSI · Segmentation": "CPSI · Segmentation", "CPSI · Risk cases": "CPSI · Risk Cases", "CPSI · Barèmes": "CPSI · Scales", "CPSI · Guide": "CPSI · Guide", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sections & Rights", "Profils AR": "AR Profiles", "Profils GAR": "GAR Profiles", "Registre paramètres": "Parameter Registry", "Types de CoC": "CoC Types", "Bacs à sable": "Sandboxes", "Audit & transport": "Audit & Transport", "Audit IT": "IT Audit", "Utilisateurs & rôles": "Users & Roles", "Guide IAM": "IAM Guide", "SSO / Fédération": "SSO / Federation" },
  DE: { "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Erweitertes Screening", "File d'alertes": "Alert-Warteschlange", "Dossiers de risque": "Risikodossiers", "Personnes / UBO": "Personen / UBO", "Chgt circonstances": "Änderung der Verhältnisse", "Custody & TA": "Custody & TA", "Settlement": "Abwicklung", "Reporting MROS": "MROS-Meldungen", "Pièces (GED)": "Dokumente (DMS)", "GED / coffre": "DMS / Tresor", "Workflow": "Workflow", "Paramétrage": "Parametrierung", "Config & Go-live": "Konfiguration & Go-live", "Référentiel AML": "GwG-Referenzdaten", "Bac à sable AML": "GwG-Sandbox", "Bac à sable Onboarding": "Onboarding-Sandbox", "Ports": "Ports", "Workflow Instances": "Workflow-Instanzen", "Formations": "Schulungen", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "KYC-Replay zum Stichtag", "Règles AML": "GwG-Regeln", "Finance Islamique": "Islamic Finance", "CPSI · Profil": "CPSI · Profil", "CPSI · Segmentation": "CPSI · Segmentierung", "CPSI · Risk cases": "CPSI · Risk Cases", "CPSI · Barèmes": "CPSI · Skalen", "CPSI · Guide": "CPSI · Leitfaden", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sektionen & Rechte", "Profils AR": "AR-Profile", "Profils GAR": "GAR-Profile", "Registre paramètres": "Parameterregister", "Types de CoC": "CoC-Typen", "Bacs à sable": "Sandboxes", "Audit & transport": "Audit & Transport", "Audit IT": "IT-Audit", "Utilisateurs & rôles": "Benutzer & Rollen", "Guide IAM": "IAM-Leitfaden", "SSO / Fédération": "SSO / Föderation" },
  IT: { "Command Center": "Command Center", "Onboarding": "Onboarding", "Screening avancé": "Screening avanzato", "File d'alertes": "Coda degli alert", "Dossiers de risque": "Dossier di rischio", "Personnes / UBO": "Persone / UBO", "Chgt circonstances": "Cambiamento di circostanze", "Custody & TA": "Custody & TA", "Settlement": "Regolamento", "Reporting MROS": "Reporting MROS", "Pièces (GED)": "Documenti (GED)", "GED / coffre": "GED / cassaforte", "Workflow": "Workflow", "Paramétrage": "Parametrizzazione", "Config & Go-live": "Config & Go-live", "Référentiel AML": "Referenziale LRD", "Bac à sable AML": "Sandbox LRD", "Bac à sable Onboarding": "Sandbox Onboarding", "Ports": "Ports", "Workflow Instances": "Istanze workflow", "Formations": "Formazione", "Octopulse OpRisk": "Octopulse OpRisk", "Rejeu KYC à date": "Replay KYC a data", "Règles AML": "Regole LRD", "Finance Islamique": "Finanza islamica", "CPSI · Profil": "CPSI · Profilo", "CPSI · Segmentation": "CPSI · Segmentazione", "CPSI · Risk cases": "CPSI · Risk cases", "CPSI · Barèmes": "CPSI · Scale", "CPSI · Guide": "CPSI · Guida", "Olivia": "Olivia", "Olivia · Runs": "Olivia · Runs", "Sections & droits": "Sezioni & diritti", "Profils AR": "Profili AR", "Profils GAR": "Profili GAR", "Registre paramètres": "Registro parametri", "Types de CoC": "Tipi di CoC", "Bacs à sable": "Sandbox", "Audit & transport": "Audit & trasporto", "Audit IT": "Audit IT", "Utilisateurs & rôles": "Utenti & ruoli", "Guide IAM": "Guida IAM", "SSO / Fédération": "SSO / Federazione" },
};
for (const l of ["EN", "DE", "IT"] as const) Object.assign(DICT[l], EXT[l]);

// ── Contenus d'écrans (tour 3 du cliquet — un bloc par écran converti, clés FR) ──
const ECRANS: Record<Exclude<Langue, "FR">, Record<string, string>> = {
  EN: { "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Custom Reporting (declared projections only — zero free-form SQL)", "Charger l'annuaire": "Load the directory", "Interroger": "Query", "ligne(s) source (scopées BACKEND) · sensibilité": "source row(s) (scoped BACKEND) · sensitivity", "Chargement de l'écran…": "Loading screen…" },
  DE: { "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Individuelles Reporting (nur deklarierte Projektionen — kein freies SQL)", "Charger l'annuaire": "Verzeichnis laden", "Interroger": "Abfragen", "ligne(s) source (scopées BACKEND) · sensibilité": "Quellzeile(n) (BACKEND-gescoped) · Sensibilität", "Chargement de l'écran…": "Bildschirm wird geladen…" },
  IT: { "BI — Reporting sur mesure (projections déclarées seulement — zéro SQL libre)": "BI — Reporting su misura (solo proiezioni dichiarate — zero SQL libero)", "Charger l'annuaire": "Caricare l'elenco", "Interroger": "Interrogare", "ligne(s) source (scopées BACKEND) · sensibilité": "riga/e sorgente (scope BACKEND) · sensibilità", "Chargement de l'écran…": "Caricamento della schermata…" },
};
for (const l of ["EN", "DE", "IT"] as const) Object.assign(DICT[l], ECRANS[l]);

export function langue(): Langue {
  try {
    const l = window.localStorage.getItem("OLIVE_LANG") as Langue | null;
    return l && LANGUES.includes(l) ? l : "FR";
  } catch { return "FR"; }
}

export function setLangue(l: Langue) {
  try { window.localStorage.setItem("OLIVE_LANG", l); } catch { /* stockage indisponible — la langue reste FR */ }
}

/**
 * Le `tr()` de la maquette : traduction si la clé existe, sinon la clé FR (écart par clé).
 * R326/LN-02 (ratifié 2026-07-29) : la clé MANQUANTE se voit — marqueur ⟦…⟧ en DEV
 * uniquement (repli FR PROPRE en prod, jamais une clé brute maquillée) ; FR = langue de
 * référence, jamais marquée (la clé EST le FR).
 */
export function traduire(l: Langue, opts?: { dev?: boolean }): (cle: string) => string {
  if (l === "FR") return (cle) => cle;
  const dev = opts?.dev ?? (typeof import.meta !== "undefined" && Boolean((import.meta as { env?: { DEV?: boolean } }).env?.DEV));
  const d = DICT[l];
  return (cle) => d[cle] ?? (dev ? `⟦${cle}⟧` : cle);
}

/**
 * R327/LN-06 : le NOMBRE suit la LOCALE de l'utilisateur, la DEVISE suit la DONNÉE —
 * jamais l'inverse. Intl fait foi par locale (les littéraux d'exemple du canon sont
 * illustratifs — consigné).
 */
export function formatMontant(montant: number, devise: string, locale: string): string {
  return new Intl.NumberFormat(locale, { style: "currency", currency: devise }).format(montant);
}
